In [1]:
import torch

In [2]:
# Manipulations
# 인덱싱: numpy처럼 인덱싱 형태로 사용 가능

x = torch.Tensor([[1,2],[3,4]])
print(x)

print(x[0,0])
print(x[:,0])
print(x[0,:])

tensor([[1., 2.],
        [3., 4.]])
tensor(1.)
tensor([1., 3.])
tensor([1., 2.])


In [3]:
# view : 텐서의 크기(size)나 모양(shape)을 변경
x = torch.randn(4,5)
print(x.shape)
print(x.size())

torch.Size([4, 5])
torch.Size([4, 5])


In [5]:
print(x,'\n')
y = x.view(20)
print(y)
print(y.shape)

tensor([[ 0.3374, -0.7201,  0.7585,  0.8171, -0.8931],
        [ 0.8075,  1.2934,  0.9806, -1.3461,  0.7738],
        [-0.7434,  1.1206, -0.1108, -1.2225, -0.2256],
        [ 1.6795, -0.9943, -0.1050,  0.7297,  1.6918]]) 

tensor([ 0.3374, -0.7201,  0.7585,  0.8171, -0.8931,  0.8075,  1.2934,  0.9806,
        -1.3461,  0.7738, -0.7434,  1.1206, -0.1108, -1.2225, -0.2256,  1.6795,
        -0.9943, -0.1050,  0.7297,  1.6918])
torch.Size([20])


In [7]:
y = x.view((2,2,5))
print(y)
print(y.shape)

tensor([[[ 0.3374, -0.7201,  0.7585,  0.8171, -0.8931],
         [ 0.8075,  1.2934,  0.9806, -1.3461,  0.7738]],

        [[-0.7434,  1.1206, -0.1108, -1.2225, -0.2256],
         [ 1.6795, -0.9943, -0.1050,  0.7297,  1.6918]]])
torch.Size([2, 2, 5])


In [10]:
# [과제]
x = torch.FloatTensor([[1,2],[3,4],[5,6],[7,8]])
print(x)

# size를 활용한 텐서 사이즈 보기
print(x.size())

# shape를 활용한 텐서 사이즈 보기
print(x.shape)

# dim을 활용한 텐서 차원 확인
print(x.dim())

# 0 차원 사이즈 확인
print(x.size(0))

# 1 차원 사이즈 확인
print(x.shape[1])

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
torch.Size([4, 2])
torch.Size([4, 2])
2
4
2


In [20]:
# 차이를 조금 익혀볼까?
import numpy as np

print(np.array([1,2,3]).shape, np.array([1,2,3]).ndim)
print(np.array([[1,2,3]]).shape, np.array([[1,2,3]]).ndim)
print(np.array([[1],[2],[3]]).shape, np.array([[1],[2],[3]]).ndim)

(3,) 1
(1, 3) 2
(3, 1) 2


In [21]:
# item(): 해당 값을 자르지 않고 반환
x = torch.randn(1)
print(x)
print(x.item())
print(x.dtype)

tensor([1.2259])
1.2258963584899902
torch.float32


In [24]:
# 스칼라값 하나만 존재할 때에만 item() 사용 가능
x = torch.randn(2)
print(x)
# print(x.item())
print(x.dtype)

tensor([-0.2823,  0.5371])
torch.float32


In [26]:
# squeeze : 차원을 축소
tensor = torch.rand(1,3,3)
print(tensor)
print(tensor.shape,'\n')
t = tensor.squeeze()
print(t)
print(t.shape) # 아마도 1개 짜리는 날려도 텐서의 모양 자체는 변하지 않으니 1 값인 차원이 있으면 그걸 날려버리는 기믹인 듯

tensor([[[0.9064, 0.9183, 0.9364],
         [0.5261, 0.2922, 0.1099],
         [0.4745, 0.1188, 0.7292]]])
torch.Size([1, 3, 3]) 

tensor([[0.9064, 0.9183, 0.9364],
        [0.5261, 0.2922, 0.1099],
        [0.4745, 0.1188, 0.7292]])
torch.Size([3, 3])


In [27]:
# unsqueeze : 차원을 증가
t = torch.rand(3,3)
print(t)
print(t.shape,'\n')
tensor = t.unsqueeze(dim=0) # 0번째, 즉 3차원 방향으로 차원을 증가시켰다.
print(tensor)
print(tensor.shape)

tensor([[0.4124, 0.6974, 0.7520],
        [0.0823, 0.7077, 0.9591],
        [0.3694, 0.5782, 0.7764]])
torch.Size([3, 3]) 

tensor([[[0.4124, 0.6974, 0.7520],
         [0.0823, 0.7077, 0.9591],
         [0.3694, 0.5782, 0.7764]]])
torch.Size([1, 3, 3])


In [28]:
tensor = t.unsqueeze(dim=2)
print(tensor)
print(tensor.shape) # 열 방향으로 차원 늘리기

tensor([[[0.4124],
         [0.6974],
         [0.7520]],

        [[0.0823],
         [0.7077],
         [0.9591]],

        [[0.3694],
         [0.5782],
         [0.7764]]])
torch.Size([3, 3, 1])


In [29]:
tensor = t.unsqueeze(dim=1)
print(tensor)
print(tensor.shape) # 행 방향으로 차원 늘리기

tensor([[[0.4124, 0.6974, 0.7520]],

        [[0.0823, 0.7077, 0.9591]],

        [[0.3694, 0.5782, 0.7764]]])
torch.Size([3, 1, 3])
