## Numpy
- 'Numerical Python'의 약자<br>
- 대규모 다차원 배열과 행렬 연산에 필요한 다양한 함수를 제공<br>
    (메모리도 적게 먹고 빠르다!)
<br>

- Numerical Python을 의미하는 Numpy는 파이썬에서 선형대수 기반의 프로그램을<br>
    쉽게 만들 수 있도록 지원하는 대표적인 패키지<br>
- 많은 머신러닝 알고리즘이 넘파이 기반으로 작성되어 있으며<br>
    알고리즘의 입출력 데이터를 넘파이 배열 타입으로 사용함<br>
- 넘파이의 기본 데이터 타입은 ndarray<br>
    ndarray를 이용해 넘파이에서 다차원 배열을 쉽게 생성하고 다양한 연산 수행<br>
    (행렬 같은 2차원 배열부터 n차까지 다양하게)
    
<br>
    
### Numpy의 특징
- 강력한 N차원 배열 객체
- 정교한 브로드캐스팅 기능
- 유용한 선형대수학, 푸리에 변환 및 난수 기능
- 푸리에 변환은 시간이나 공간에 대한 함수를 시간 또는 공간 주파수 성분으로 분해하는 변환
- 범용적 데이터 처리에 사용 가능한 다차원 컨테이너

In [1]:
!pip install numpy

In [2]:
import numpy as np

z = np.arange(10) # 0~9까지 10개 숫자의 1차원 배열을 출력
print(z, type (z)) # 넘파이의 기본 데이터 타입은 ndarray

[0 1 2 3 4 5 6 7 8 9] <class 'numpy.ndarray'>


In [4]:
import numpy as np

my_arr = np.arange(1000000)
my_list = list(range(100000))

In [6]:
%time for _ in range(10): my_arr2 = my_arr*2

Wall time: 9.03 ms


In [8]:
%time for _ in range(10): my_list2 = [x*2 for x in my_list]

Wall time: 43 ms


In [16]:
# 배열 연산
# np.random.randn - 가우시안 표준 정규분포(평균이 0이고 표준편차가 1인 분포)에서 난수 행렬 array 생성
data = np.random.randn(2,3) # 표준 정규분포로 구성되는 2행 3열 매트릭스
print(data, '\n')
print(data*10, '\n') # 행렬 자체에다 연산이 가능하다!
print(data+data)

[[ 1.11452506 -0.57950103 -2.4025284 ]
 [-0.83737288  0.79928533  0.70650401]] 

[[ 11.14525058  -5.79501032 -24.02528402]
 [ -8.37372882   7.99285332   7.0650401 ]] 

[[ 2.22905012 -1.15900206 -4.8050568 ]
 [-1.67474576  1.59857066  1.41300802]]


In [20]:
print(data.shape) # 행렬의 크기(2행 3열이겠지?)
print(data.dtype) # 데이터의 타입(ndarray겠지?) - float64는 실수 형태이니까~
print(data.ndim) # 데이터의 차원(2차원이겠지?)

(2, 3)
float64
2


## Numpy 차원

<img src = "numpy차원.jpg" width = 700px;>
<br>
axis 0: 행<br>
axis 1: 열<br>
axis 2: 깊이<br>
3D는 공간, 그 이상 고차원부터는 수학적으로만 계산 가능(이미지화 불가능)

In [13]:
data2 = [[1,2,3,4],[5,6,7,8]]
print(type(data2),'\n')
arr2 = np.array(data2)
print(arr2,type(arr2))

<class 'list'> 

[[1 2 3 4]
 [5 6 7 8]] <class 'numpy.ndarray'>


In [14]:
print(arr2.shape,'\n') # 2행 1열이겠지요? (2행 4열이었다고 합니다)
print(arr2.dtype,'\n') # 리스트겠지요? (정수 타입이었다고 합니다)
print(arr2.ndim,'\n') # 2차원이겠지요?


# []끼리 묶어진 것을 한 덩이로 보는 게 아니라, 같은 행이어서 묶었다고 생각해 봐
# 그러면 [[]/[]]로 2행, [///] 괄호의 내용으로 열 구분이 가능해질 거야

(2, 4) 

int32 

2 



In [4]:
import numpy as np
import pandas as pd
a = {'빨강':2,'파랑':7,'초록':21}
pd.DataFrame(a,index = a.keys())


빨강  파랑  초록
빨강   2   7  21
파랑   2   7  21
초록   2   7  21

In [15]:
# 1차원 배열로 3개의 데이터
array1 = np.array([1,2,3]) # 1차원 배열이당
print(array1,type(array1),array1.shape) #(행,렬)이 아닌 (행,)의 형태로 출력

# 우리가 보통 행렬이라 말하고 (행,렬)로 나타내긴 하지만 1차원 배열이면
# (행,) 이렇게 출력해 준다
# 왜냐면 1차원이니까~ 열이 필요가 없는 거지~
# 근데 만약 저게 2차원 배열(1행 3열)이었음 한다면 양옆에 []만 새로 쳐 주면 됨

[1 2 3] <class 'numpy.ndarray'> (3,)


In [27]:
# [연습문제] 2차원 배열로 2개의 row와 3개의 column으로 구성되 6개의 데이터

array2 = np.array([[1,2,3],[4,5,6]])
print(array2,type(array2),array2.shape)

[[1 2 3]
 [4 5 6]] <class 'numpy.ndarray'> (2, 3)


In [36]:
# [연습문제] 2차원 배열로 1개의 row와 3개의 column으로 구성되 3개의 데이터
array3 = np.array(['김','이','박']) # 1차원 배열
print(array3,type(array3),array3.shape,array3.ndim)

array4 = np.array([['김','이','박']]) # 2차원 배열. []로 한 번 더 감싸주어 차원을 만들었다.
print(array4,type(array4),array4.shape,array4.ndim)

['김' '이' '박'] <class 'numpy.ndarray'> (3,) 1
[['김' '이' '박']] <class 'numpy.ndarray'> (1, 3) 2


In [35]:
# [자체문제] 1행 n열은 많이 했으니 n행 1열 해볼까?
ar0 = np.array([[1],[2],[3]])
print(ar0,type(ar0),ar0.shape,ar0.ndim)

[[1]
 [2]
 [3]] <class 'numpy.ndarray'> (3, 1) 2


In [43]:
# [연습문제] 3차원 만들어 보기
ar3d = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]]])
print(ar3d,type(ar3d),ar3d.shape,ar3d.ndim)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]] <class 'numpy.ndarray'> (2, 3, 3) 3


한 장 한 장씩 순차적으로 깊이를 만들었다고 생각하셈<br>
2,3,4면 3행 4열의 배열이 2장이라고

In [ ]:
# 경고 메시지 처리
import warnings
warnings.filterwarnings('ignore') # 경고문구 무시함. 어떤 상황의 오류를 무시한다는 건지 못 들음

배열 생성 및 초기화
- Numpy는 원하는 shape로 배열을 설정하고 각 요소를 특정값으로 초기화하는<br>
   zeros, ones, full, eye 함수 제공<br>
   (zeros는 각 요소를 0으로, ones는 1로 초기화)
- 파라미터로 입력한 배열과 같은 shape의 배열을 만드는 zeros_like, ones_like, full_like 함수도 제공

In [53]:
print(np.zeros(10),'\n') # 0이 10개인 1차원 배열 출력
print(np.zeros((3,6)),'\n') # 0으로만 구성된 3행 6열의 2차원 배열 출력
print(np.zeros((2,3,2)),'\n') # 0으로만 구성된, 2행 3열 깊이 2인 3차원 배열 출력
# 출력값 뒤에 . 찍힌 건 실수 형태 표현이라서

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]] 

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]] 



In [18]:
print(np.ones(10),'\n') # 1이 10개인 1차원 배열 출력
print(np.ones((3,6)),'\n') # 1로만 구성된 3행 6열의 2차원 배열 출력
print(np.ones((2,3,2))) # 1로만 구성된, 3행 2열 깊이 2인 3차원 배열 출력

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] 

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]] 

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [54]:
a = np.full((2,3),5) # 5로만 구성된 2행 3열의 2차원 배열 출력
print(a)

[[5 5 5]
 [5 5 5]]


In [57]:
b = np.eye(3) # E 기억나니...? 해당 크기의 단위행렬을 만들어 준단다
print(b)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [62]:
# arange 함수: Python의 range 함수의 배열 버전
arr1 = np.arange(15)
arr2 = range(15)
print(arr1,'\n',arr2)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14] 
 range(0, 15)


In [65]:
arr3 = arr1.reshape((3,5))
# 위에서 만든 arr1의 요소가 15개이기 때문에 3*5든, 5*3이든, 요소가 총 15개가 되도록 해야 함
print(arr3)
print()
arr3rd = arr1.reshape((1,3,5))
print(arr3rd)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]]


In [66]:
# [연습문제] array1을 생성하고 reshape 함수를 이용, (5,2) 2차원 배열을 생성한 후 크기를 같이 출력하세요.
array1 = np.arange(10)
array2 = array1.reshape(5,2)
print(array2, array2.ndim)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]] 2


In [68]:
# [연습문제] 0~29까지의 1차원 배열을 생성한 후 다시 2, 3차원 배열로 변환하여 출력하세요.

ar1 = np.arange(30)
ar2 = ar1.reshape(5,6)
ar3 = ar1.reshape(2,3,5)

print(ar2,'\n',ar2.ndim,'\n')
print(ar3,'\n',ar3.ndim)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]] 
 2 

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]] 
 3


In [73]:
# reshape(-1,-1)를 이용, 차원 변경
ar1 = np.arange(30)
ar12 = ar1.reshape(5,-1) # 1차원 배열 ar1에 대해 행은 5개, 나머지 열의 수는 가능한 수로 출력
print(ar12,'\n',ar12.ndim,'\n') # 알아서 6열로 배치

ar13 = ar1.reshape(-1,2,5) # -1 자리에 들어갈 수 있는 숫자는 3뿐이지
print(ar13,'\n',ar13.ndim,'\n')

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]] 
 2 

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]] 
 3 



In [76]:
# [연습문제] 2차원 배열을 1, 3차원으로 재변환
ar2 = np.array([[1,2,3],[4,5,6]])
ar1 = ar2.reshape(-1,) # 6,이라고 써도 되지만 어차피 가능한 경우의 수가 1개라서 -1, 써도 됨
ar3 = ar2.reshape(2,-1,3)
print(ar1,'\n')
print(ar3)

[1 2 3 4 5 6] 

[[[1 2 3]]

 [[4 5 6]]]


In [79]:
# [연습문제] 3차원 배열을 1, 2차원으로 재변환
ar3 = np.arange(30).reshape(3,2,5)
ar31 = ar3.reshape(-1,)
ar32 = ar3.reshape(3,-1) # -1 자리에는 경우의 수가 1개밖에 없는 경우에 편리하게 적용할 수 있다!

print(ar31,'\n')
print(ar32)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29] 

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]]


## 행렬의 종류
- 정방행렬: 행과 열의 수가 같은 행렬(n*n)
- 대각행렬: 주 대각선 원소를 제외한 모든 원소들이 0인 정방행렬<br>
    (eye로 만든 단위행렬/항등행렬을 포함, 해당 행렬에 n을 곱한 형태가 대각행렬의 기본 모양)
- 항등행렬(단위행렬): 행렬 곱셈 연산에 항등원으로 작용하는 행렬
- 영행렬: 모든 원소가 0인 행렬<br>
    zeros 함수로 만든 정방행렬이 영행렬이다.
- 전치행렬: 주 대각선 원소를 기준으로 행과 열을 바꿔주는 행렬
- 직교행렬: 행렬 A의 역행렬 a의 전치행렬<br>
    A의 전치행렬과 A 행렬을 곱하였을 때 항등행렬이 나오는 행렬

In [83]:
# 정방행렬
jar = np.arange(25).reshape(5,5)
jar1 = np.full((3,3),7)
print(jar,'\n',jar1)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]] 
 [[7 7 7]
 [7 7 7]
 [7 7 7]]


In [84]:
# 항등행렬, 단위행렬
a = np.eye(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [86]:
# 영행렬
a = np.zeros((5,5))
print(a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


## ndarray 데이터 형태 지정 및 변경
<img src ="데이터형태.jpg" width=700px>

dtype 함수를 통해서 나오는 결과값을 정리했음<br>
unit 아니고 uint임. 언사인드 인테걸스.<br>
int는 부호 있는 정수형, uint는 부호 없는 정수형<br>
뒤의 숫자는 16비트, 64비트 뭐 이런 얘기

In [89]:
arr1 = np.array([1,2,3],dtype=np.float64) # 실수형이니까 n. 형태로 나올 것이다
arr2 = np.array([1,2,3],dtype=np.int32)
print(arr1,arr1.dtype,'\n',arr2,arr2.dtype)

[1. 2. 3.] float64 
 [1 2 3] int32


In [93]:
# 타입 변경
arr = np.array([1,2,3,4,5])
print(arr,arr.dtype)
farr = arr.astype(np.float64)
print(farr,farr.dtype)

[1 2 3 4 5] int32
[1. 2. 3. 4. 5.] float64


In [97]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [99]:
# empty 함수: shape와 dtype을 입력받아 초기화되지 않은 배열을 만들어 준다. cf. zeros 함수
# 메모리에 남아 있는 걸 그대로 가져오기 때문에 이전 값을 불러온다.
# 위에서 ones 함수를 실행했기 때문에 1이 나오고, 만약 zeros를 썼다면 0이 나오겠지?

# empty 함수를 실행할 때마다 값이 다른 것을 확인할 수 있다.
# 이는 해당 메모리 영역에 어떤 데이터가 남아 있었든 상관 없이 있는 그대로 영역의 주소만 알려줄 뿐
# 초기화는 사용자에게 맡기기 때문임.

# zeros는 0으로 초기화 된 그릇
# ones는 1로 초기화 된 그릇
# full은 해당 숫자로 가득 찬 그릇
# empty는 초기화 그런 거 없이 진짜 빈 그릇이라 이전 정보가 담겨 나옴

print(np.empty(shape=(10,),dtype=np.int8))

[1 1 1 1 1 1 1 1 1 1]


In [266]:
# 문자열 타입으로 배열 만들기
# arr = np.array([1,2,3,4],dtype='S') - 이건 타입 코드로 작성
arr = np.array(([1,2,3,4],[5,6,7,8]),dtype=np.string_) # 이건 타입으로 작성
print(arr,arr.dtype)
arr1 = arr.astype(float) # 문자열 타입을 실수형으로도 변환했다!
# arr1 = arr.astype('float64') 로도 표현 가능. 64를 다른 숫자로 바꾼다거나 할 때에.
print(arr1,arr1.dtype)

# S1 << S 뒤의 숫자는 문자열의 길이를 의미한다...고 하는데
# 지금 위의 배열은 전부 글자가 1개뿐이라 S1로 나왔지

ar_ = np.array([12,234,5678,9101112],dtype=np.string_)
print(ar_.dtype) # 인덱스 3번의 글자 길이가 7이라서 S7 출력

[[b'1' b'2' b'3' b'4']
 [b'5' b'6' b'7' b'8']] |S1
[[1. 2. 3. 4.]
 [5. 6. 7. 8.]] float64
|S7


In [116]:
# [연습문제] 정수와 실수로 구성된 list_e = [1.2,2.3,3]을
# numpy를 이용하여 실수형과 정수형으로 각각 출력하세요.
list_e = [1.2,2.3,3] # 애초에 실수가 섞여 있어서 실수형으로 분류됨
int_e = np.array(list_e,dtype='int64')
float_e = np.array(list_e).astype(float)
print(np.array(list_e),np.array(list_e).dtype,'\n',int_e,int_e.dtype,'\n',float_e,float_e.dtype)

[1.2 2.3 3. ] float64 
 [1 2 3] int64 
 [1.2 2.3 3. ] float64


In [122]:
# 배열의 산술 연산
# arr = np.array([[1,2,3],[4,5,6]])
arr = np.arange(1,7).reshape(2,3)
print(arr,arr.dtype)
print(arr+arr)
print(arr-arr)
print(arr*arr)
print(arr/arr)

[[1 2 3]
 [4 5 6]] int32
[[ 2  4  6]
 [ 8 10 12]]
[[0 0 0]
 [0 0 0]]
[[ 1  4  9]
 [16 25 36]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [126]:
# Boolean
arr = np.arange(1,7).reshape(2,3)
arr2 = np.array([[0.,4.,1.],[7.,2.,12.]]) # 정수형 뒤에 . 붙여 놓으면 알아서 실수형으로 출력해 줌
arr > arr2

array([[ True, False,  True],
       [False,  True, False]])

In [262]:
# 기본 사칙연산 - 수식과 함수
v1 = np.arange(1,10).reshape(3,-1)
v2 = np.arange(11,20).reshape(3,-1)

print(v1+v2)
print(np.add(v1,v2),'\n')
print(v2-v1)
print(np.subtract(v2,v1),'\n') # EXTRACT와 헷갈리지 말자!
print(v1*v2)
print(np.multiply(v1,v2),'\n')
print(v2/v1) # round는 안 먹히네 ㅎㅎ...?
print(np.divide(v2,v1).round(2)) # round를 쓰고 싶으면 이렇게 하자!

[[12 14 16]
 [18 20 22]
 [24 26 28]]
[[12 14 16]
 [18 20 22]
 [24 26 28]] 

[[10 10 10]
 [10 10 10]
 [10 10 10]]
[[10 10 10]
 [10 10 10]
 [10 10 10]] 

[[ 11  24  39]
 [ 56  75  96]
 [119 144 171]]
[[ 11  24  39]
 [ 56  75  96]
 [119 144 171]] 

[[11.          6.          4.33333333]
 [ 3.5         3.          2.66666667]
 [ 2.42857143  2.25        2.11111111]]
[[11.    6.    4.33]
 [ 3.5   3.    2.67]
 [ 2.43  2.25  2.11]]


In [150]:
arr = np.random.randn(2,3)

print(arr)
print(arr.mean().round(4)) # 산술평균
print(arr.mean(axis=0)) # 열을 따라 계산된 평균. 열의 개수만큼 나옴
print(arr.mean(axis=1)) # 행을 따라 계산된 평균. 행의 개수만큼 나옴. 헷갈리지 마~
print(arr.sum().round(4)) # 모든 항목을 전부 더하고 소수점 4자리까지 깎아치기
print(arr.cumprod()) # 각 원소들끼리의 누적 곱

[[-0.10763935  0.33076305 -0.78023307]
 [-1.3103681   1.11074813  0.39702184]]
-0.06
[-0.70900373  0.72075559 -0.19160561]
[-0.18570312  0.06580062]
-0.3597
[-0.10763935 -0.03560312  0.02777873 -0.03640036 -0.04043164 -0.01605224]


In [161]:
# 인덱싱, 슬라이싱

ar2d = np.arange(1,10).reshape(3,-1)
print(ar2d[2])
print(ar2d[2][2])
print(ar2d[:,0])
print(ar2d[:2,:])

[7 8 9]
9
[1 4 7]
[[1 2 3]
 [4 5 6]]


In [164]:
# [연습문제] 2차원 배열 ar2d에서 [3,6],[[1,2],[4,5]]를 각각 출력하세요.
ar2d = np.arange(1,10).reshape(3,-1)
print(ar2d[:2,2])
print(ar2d[:2,:2])

[3 6]
[[1 2]
 [4 5]]


In [20]:
# [연습문제] 2차원 배열 ar2d를 다른 방식으로 아래와 같이 출력하세요.
# [[1,2,3]
#  [4,5,6]]
ar2d = np.arange(1,10).reshape(3,-1)
print(ar2d[:2,:]) # 리스트로 묶어서 범위 지정해 줘도 된다! [(0,1),:]도 되고

[[1 2 3]
 [4 5 6]]


In [183]:
ar = np.arange(30).reshape(5,-1)
print(ar)
# [14,15,16]
print(ar[2,(2,3,4)]) # [2],[2:5]
# [3,9]
print(ar[:2,3]) # [0,1],3
# [1,7,13]
print(ar[:3,1]) # [0,1,2],1

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
[14 15 16]
[3 9]
[ 1  7 13]


In [185]:
# 배열을 리스트로 변환
arli = ar.tolist()
print(arli,'\n',type(arli))

[[0, 1, 2, 3, 4, 5], [6, 7, 8, 9, 10, 11], [12, 13, 14, 15, 16, 17], [18, 19, 20, 21, 22, 23], [24, 25, 26, 27, 28, 29]] 
 <class 'list'>


In [188]:
# Boolean indexing
ar1d = np.arange(1,10)
print(ar1d)
arbl = ar1d[ar1d>5] # True인 값만 반환
print(arbl)
print(ar1d>5)

[1 2 3 4 5 6 7 8 9]
[6 7 8 9]
[False False False False False  True  True  True  True]


In [190]:
# [연습문제] ar1d에서 일반 인덱스와 불린을 이용해 각각 [6,7,8,9]를 출력해 보세요.
ar1d = np.arange(1,10)
# 일반 인덱스
print(ar1d[5:])
# Boolean indexing
arbl = ar1d[ar1d>5]
print(arbl)

[6 7 8 9]
[6 7 8 9]


In [191]:
# [연습문제] 1~14까지의 ndarray를 만들어 array_e로 저장하고
# (array_e/2)>5를 만족하는 값을 불린 인덱싱으로 출력
array_e = np.arange(1,15)
bl_e = array_e[(array_e/2)>5]
print(bl_e)

[11 12 13 14]


In [267]:
names = np.array(['Bob','Joe','Will','Bob','Will','Joe','Joe'])
data = np.random.randn(7,4) # 이건 걍 한 거임.

print(data)
print(names == "Bob") # 0, 3번째 인덱스만 True
print(data[names == "Bob"]) # 1행과 4행만 출력됨
print()
print(data[names=="Bob",2:]) # 조건 만족하는 1,4행에서 3,4열 부분만 출력
print(data[names!="Bob"])
print(data[(names == "Bob")|(names=="Will")])

# 불리언에선 파이썬 예약어인 and, or를 쓸 수 없음
# 대신 &와 |를 쓰도록 하자! 

[[ 0.16340854 -0.02944818 -1.56923922  0.93952409]
 [-1.38269477  0.57026719  0.29464956  0.02241067]
 [-0.39488217 -2.16186948 -0.81998176 -0.91745489]
 [-0.42668411  0.08161055  0.56825067  0.76642641]
 [ 1.71586869 -0.0060645   0.51508091  0.02054131]
 [ 0.52711889  0.06525407  0.12086259 -0.14612327]
 [-0.84012465  0.26791252 -0.40341937  0.20179841]]
[ True False False  True False False False]
[[ 0.16340854 -0.02944818 -1.56923922  0.93952409]
 [-0.42668411  0.08161055  0.56825067  0.76642641]]

[[-1.56923922  0.93952409]
 [ 0.56825067  0.76642641]]
[[-1.38269477  0.57026719  0.29464956  0.02241067]
 [-0.39488217 -2.16186948 -0.81998176 -0.91745489]
 [ 1.71586869 -0.0060645   0.51508091  0.02054131]
 [ 0.52711889  0.06525407  0.12086259 -0.14612327]
 [-0.84012465  0.26791252 -0.40341937  0.20179841]]
[[ 0.16340854 -0.02944818 -1.56923922  0.93952409]
 [-0.39488217 -2.16186948 -0.81998176 -0.91745489]
 [-0.42668411  0.08161055  0.56825067  0.76642641]
 [ 1.71586869 -0.0060645   0.5

In [211]:
# 음수인 자료를 모두 0으로 바꿔서 출력
data = np.random.randn(4,4)
data[data<0] = 0
print(data)

[[0.         0.         0.         1.52222034]
 [0.         0.65394781 0.         1.15146403]
 [0.         0.         0.         0.        ]
 [0.62613043 0.         0.06885662 0.40768233]]


In [16]:
# nonzero 함수
# 배열에서 0이 아닌 값들의 '인 덱 스'를 반환해 준다

np.nonzero(np.arange(10))

(array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int64),)

In [33]:
# Fancy indexing

arr = np.empty((8,4))
print(arr)
for i in range(8):
    arr[i] = i
print(arr)

print(arr[[4,3,0,6]]) # 행 인덱스가 4,3,0,6인 것만 출력
print(arr[[-3,-5,-7]]) # 행 인덱스가 밑에서 3번째, 5번째, 7번째인 것을 출력

[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]
 [5. 5. 5. 5.]
 [6. 6. 6. 6.]
 [7. 7. 7. 7.]]
[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]
 [5. 5. 5. 5.]
 [6. 6. 6. 6.]
 [7. 7. 7. 7.]]
[[4. 4. 4. 4.]
 [3. 3. 3. 3.]
 [0. 0. 0. 0.]
 [6. 6. 6. 6.]]
[[5. 5. 5. 5.]
 [3. 3. 3. 3.]
 [1. 1. 1. 1.]]


In [22]:
arr = np.arange(32).reshape(8,4)
print(arr,'\n')
print(arr[[1,5,7,2],[0,3,1,2]]) # 이건 (1,0),(5,3),(7,1),(2,2)를 뽑아서 어레이로 반환함
print(arr[[1,5,7,2]])
print(arr[[1,5,7,2]][:,[0,3,1,2]]) # 뒤의 인자의 경우, 행은 전부 선택, 열 순서만 이렇게 출력

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]] 

[ 4 23 29 10]
[[ 4  5  6  7]
 [20 21 22 23]
 [28 29 30 31]
 [ 8  9 10 11]]
[[ 4  7  5  6]
 [20 23 21 22]
 [28 31 29 30]
 [ 8 11  9 10]]


In [32]:
# 배열 전치와 축 바꾸기
# 행과 열을 맞바꾼다!
# T 함수를 써도 되고 np.transpose를 써도 되고~

arr = np.arange(15).reshape(3,5)
print(arr,'\n')
print(arr.T)
print(np.transpose(arr))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]] 

[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [4]:
# [과제] zeros_like, ones_like, full_like 함수를 예시로 하나씩만 만들어 보자.
# 파라미터 자리에 변수 들어와야 한다고 함. 그 변수랑 똑같은 사이즈의 해당 내용을 출력한다고.
import numpy as np

# ar0 = np.zeros((3,3))
# ar1 = np.ones((2,3))
ar0 = np.arange(0,10,2)
ar1 = np.arange(0,11,2).reshape(2,-1)
arf = np.arange(6).reshape(3,2)
print(np.zeros_like(ar0)) # ar0 배열의 크기와 똑같은 행렬을 0으로 채워서 출력
print(np.ones_like(ar1)) # ar1 배열의 크기와 똑같은 행렬을 1로 채워서 출력
print(np.full_like(arf,5,dtype=float)) # arf 배열의 크기와 똑같은 행렬을 해당 수로 채워서 출력

[0 0 0 0 0]
[[1 1 1]
 [1 1 1]]
[[5. 5.]
 [5. 5.]
 [5. 5.]]


In [9]:
# [과제] 1 ~ 100까지 정수에서 3의 배수인 것만을 출력(for문과 배열 두가지 방식)

# for문
li =[]
for i in range(1,101):
    if i%3==0: li.append(i)
print(li)

# 배열
ar3 = np.arange(1,101)
print(ar3[ar3%3==0])

[3, 6, 9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99]
[ 3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69 72
 75 78 81 84 87 90 93 96 99]


In [10]:
# [과제] 1 ~ 100까지 정수에서 5의 배수이면서 2의 배수인 것만을 출력(for문과 배열 두가지 방식)

# for문
li=[]
for i in range(1,101):
    if i%10==0:
        li.append(i)
print(li)

# 배열
ar10 = np.arange(1,101)
print(ar10[ar10%10==0])

[10, 20, 30, 40, 50, 60, 70, 80, 90, 100]
[ 10  20  30  40  50  60  70  80  90 100]


In [238]:
# [과제] 표준정규분포로 구성된 5행 5열 다차원 배열을 생성하고 함수를 이용하여 평균과 표준편차를 구하세요.
arr = np.random.randn(5,5)
print(arr)
print(f'전체 평균: {arr.mean().round(4)}')
print(f'행 방향 평균: {arr.mean(axis=1)}')
print(f'열 방향 평균: {arr.mean(axis=0)}')
print(f'표준편차: {arr.std().round(4)}')

[[ 1.24237644 -0.48162387  1.34126797 -0.74201681 -0.76633299]
 [ 0.03500337  1.03510124  0.20396    -0.62086646  0.88086019]
 [ 0.18301655  0.98525456  0.95512192 -1.60636576  0.08986724]
 [ 0.61821458 -0.64651648  0.18739048  0.64671374  0.58958905]
 [ 0.56902407 -0.12822631 -0.90910246 -1.09114019 -0.85096274]]
전체 평균: 0.0688
행 방향 평균: [ 0.11873415  0.30681167  0.1213789   0.27907827 -0.48208153]
열 방향 평균: [ 0.529527    0.15279783  0.35572758 -0.6827351  -0.01139585]
표준편차: 0.8014


In [241]:
# [과제] 현재 사용하고 있는 numpy의 버전을 출력하세요.
!pip show numpy

Name: numpy
Version: 1.21.2
Summary: NumPy is the fundamental package for array computing with Python.
Home-page: https://www.numpy.org
Author: Travis E. Oliphant et al.
Author-email: 
License: BSD
Location: c:\cakd5\sw\anaconda3\envs\cakd5\lib\site-packages
Requires: 
Required-by: tensorflow, tensorboard, seaborn, scipy, scikit-learn, pandas, opt-einsum, numexpr, mkl-random, mkl-fft, matplotlib, Keras, Keras-Preprocessing, Keras-Applications, h5py, Bottleneck


In [12]:
print(np.__version__)

1.21.2


In [245]:
# [과제] numpy 함수의 도움말 기능을 볼수 있는 방법을 수행하여 add 함수의 가이드를 출력하세요.
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [13]:
help(np.add)

Help on ufunc object:

add = class ufunc(builtins.object)
 |  Functions that operate element by element on whole arrays.
 |  
 |  To see the documentation for a specific ufunc, use `info`.  For
 |  example, ``np.info(np.sin)``.  Because ufuncs are written in C
 |  (for speed) and linked into Python with NumPy's ufunc facility,
 |  Python's help() function finds this page whenever help() is called
 |  on a ufunc.
 |  
 |  A detailed explanation of ufuncs can be found in the docs for :ref:`ufuncs`.
 |  
 |  **Calling ufuncs:** ``op(*x[, out], where=True, **kwargs)``
 |  
 |  Apply `op` to the arguments `*x` elementwise, broadcasting the arguments.
 |  
 |  The broadcasting rules are:
 |  
 |  * Dimensions of length 1 may be prepended to either array.
 |  * Arrays may be repeated along dimensions of length 1.
 |  
 |  Parameters
 |  ----------
 |  *x : array_like
 |      Input arrays.
 |  out : ndarray, None, or tuple of ndarray and None, optional
 |      Alternate array object(s) in whic

In [257]:
# [과제] zeros 함수를 이용해서 아래와 같이 출력하세요.
# array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])
ar0 = np.zeros(10).astype(float)
ar0[4] = 1
ar0

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [251]:
# [과제] 인덱싱을 이용하여 아래 배열을 내림차순으로 정렬하세요.
# [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
arr = np.arange(10)
print(arr[::-1])

[9 8 7 6 5 4 3 2 1 0]


In [15]:
# [과제] [1,2,0,0,4,0]에서 zero가 아닌 인덱스를 배열 형태로 출력하세요.
# nonzero 함수를 쓰는가 아니냐를 보는 것이었음

arr = np.array([1,2,0,0,4,0])
# arr_= arr[arr!=0]
# print(arr_)
np.nonzero(arr)

(array([0, 1, 4], dtype=int64),)