In [1]:
import numpy as np

In [2]:
# 전치
arr = np.random.randint(1,10,size=(5,5))
print(arr,'\n',arr.T,'\n',np.transpose(arr))

[[9 4 3 2 5]
 [9 4 1 9 6]
 [3 6 4 3 2]
 [1 5 9 1 9]
 [5 6 9 9 2]] 
 [[9 9 3 1 5]
 [4 4 6 5 6]
 [3 1 4 9 9]
 [2 9 3 1 9]
 [5 6 2 9 2]] 
 [[9 9 3 1 5]
 [4 4 6 5 6]
 [3 1 4 9 9]
 [2 9 3 1 9]
 [5 6 2 9 2]]


In [3]:
# 행렬 곱, 내적

arr = np.arange(1,26).reshape(5,5)
print(arr)
print(arr.T)
np.dot(arr.T,arr) # 앞 행렬의 행과 뒷 행렬의 열을 곱해서 다 더한 값을 해당 위치에 넣은 결과임
# 일반적인 행렬 곱 계산이라 보면 된다

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[[ 1  6 11 16 21]
 [ 2  7 12 17 22]
 [ 3  8 13 18 23]
 [ 4  9 14 19 24]
 [ 5 10 15 20 25]]


array([[ 855,  910,  965, 1020, 1075],
       [ 910,  970, 1030, 1090, 1150],
       [ 965, 1030, 1095, 1160, 1225],
       [1020, 1090, 1160, 1230, 1300],
       [1075, 1150, 1225, 1300, 1375]])

In [4]:
# 축 스왑
a = np.arange(6).reshape(2,3)
print(a,'\n')
y = np.swapaxes(a, 0,1) # a에 대해 행과 열을 바꿔라. 0은 2차원(열), 1은 1차원(행)
print(y,'\n',a.T,'\n',np.transpose(a))
print(y == a.T)

[[0 1 2]
 [3 4 5]] 

[[0 3]
 [1 4]
 [2 5]] 
 [[0 3]
 [1 4]
 [2 5]] 
 [[0 3]
 [1 4]
 [2 5]]
[[ True  True]
 [ True  True]
 [ True  True]]


In [5]:
# [연습문제] 1~100을 아래와 같이 출력해 보세요
#[[  1   2   3   4   5   6   7   8   9  10]
# [ 20  19  18  17  16  15  14  13  12  11]
# [ 21  22  23  24  25  26  27  28  29  30]
# [ 40  39  38  37  36  35  34  33  32  31]
# [ 41  42  43  44  45  46  47  48  49  50]
# [ 60  59  58  57  56  55  54  53  52  51]
# [ 61  62  63  64  65  66  67  68  69  70]
# [ 80  79  78  77  76  75  74  73  72  71]
# [ 81  82  83  84  85  86  87  88  89  90]
# [100  99  98  97  96  95  94  93  92  91]] <class 'numpy.ndarray'>


In [6]:
ar = np.arange(1,101).reshape(10,10)
for i in range(10):
    if i%2==1:
        ar[i] = ar[i,::-1]
print(ar,type(ar))

[[  1   2   3   4   5   6   7   8   9  10]
 [ 20  19  18  17  16  15  14  13  12  11]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 40  39  38  37  36  35  34  33  32  31]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 60  59  58  57  56  55  54  53  52  51]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 80  79  78  77  76  75  74  73  72  71]
 [ 81  82  83  84  85  86  87  88  89  90]
 [100  99  98  97  96  95  94  93  92  91]] <class 'numpy.ndarray'>


In [7]:
# 또는! 인덱싱 기능을 이용하여~
ar = np.arange(1,101).reshape(10,10)
ar[[1,3,5,7,9]] = ar[[1,3,5,7,9]][:,::-1]
print(ar,type(ar))

[[  1   2   3   4   5   6   7   8   9  10]
 [ 20  19  18  17  16  15  14  13  12  11]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 40  39  38  37  36  35  34  33  32  31]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 60  59  58  57  56  55  54  53  52  51]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 80  79  78  77  76  75  74  73  72  71]
 [ 81  82  83  84  85  86  87  88  89  90]
 [100  99  98  97  96  95  94  93  92  91]] <class 'numpy.ndarray'>


In [8]:
# (0,1,2) - 순서대로 3차원, 2차원, 1차원
# 2차원 배열 행렬과 헷갈리면 안 돼!!

# 0 - 3차원 깊이
# 1 - 2차원 행
# 2 - 1차원 열

# axis 0(깊이), 1(행), 2(열)
# 차원을 모두 바꿔보자! (3차원, 2차원, 1차원)->(2차원,1차원,3차원) 0,1,2 -> 1,2,0
# 1차원 열, 2차원 행, 3차원 깊이
# 행이 페이지 수라고 생각하면 편함.윗장, 밑장의 개수가 행의 수

a = np.arange(36).reshape(2,3,-1) # 1차원 열 6개, 2차원 행 3개, 3차원 깊이 2개
print(a,a.shape,'\n')
y = np.transpose(a,(1,2,0)) # 2차원 성분을 3차원으로, 3차원 성분은 1차원으로, 1차원 성분은 2차원
print(y,y.shape,'\n') # 1차원 열 2개, 2차원 행 6개, 3차원 깊이 3개

[[[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]
  [12 13 14 15 16 17]]

 [[18 19 20 21 22 23]
  [24 25 26 27 28 29]
  [30 31 32 33 34 35]]] (2, 3, 6) 

[[[ 0 18]
  [ 1 19]
  [ 2 20]
  [ 3 21]
  [ 4 22]
  [ 5 23]]

 [[ 6 24]
  [ 7 25]
  [ 8 26]
  [ 9 27]
  [10 28]
  [11 29]]

 [[12 30]
  [13 31]
  [14 32]
  [15 33]
  [16 34]
  [17 35]]] (3, 6, 2) 



In [9]:
# 나머지를 구할 경우 사용하는 함수
val1 = np.array([15,30,45])
val2 = np.array([2,7,9])
print(np.mod(val1,val2))
print(np.remainder(val1,val2))

[1 2 0]
[1 2 0]


In [10]:
# 각 수의 역수를 구해주는 함수
val = np.array([0.85,1.85,100])
print(np.reciprocal(val).round(4),'\n')

val1 = np.array([100],dtype=int)
print(val1,'\n')
print(np.reciprocal(val1,dtype=float))

[1.1765 0.5405 0.01  ] 

[100] 

[0.01]


In [11]:
# 승수의 결과값을 표시해 주는 함수
v1 = np.array([2,10,15])
v2 = np.array([1,2,3])
print(np.power(v1,2),'\n',np.power(v1,v2))

[  4 100 225] 
 [   2  100 3375]


In [12]:
# 그것이 표준 정규분포이니까...
arr = np.random.randn(10000000) # 집단을 무한히 늘릴수록 평균은 0, 표준편차는 1에 가까워진다.
print(arr.mean(),'\n')
print(arr.std())

0.00025743979333665184 

1.0001374683061406


In [13]:
# 양수인 원소의 개수
arr = np.random.randn(10)
(arr>0).sum()

6

In [14]:
# 하나 이상의 값이 True라면 any, 모두가 True여야 한다면 all
bools = np.array([False, False, True, True])
print(bools.any(),bools.all())

True False


In [15]:
# 삼항식의 벡터화 버전
arr = np.random.randn(4,4)
print(arr,'\n')
np.where(arr>0,2,-2) # arr이 0보다 크면 2, 작으면 -2 반환

[[ 0.05428054  0.4339411  -1.08880494 -0.83544476]
 [ 1.02588133 -0.0404686  -0.08926639 -0.76061744]
 [ 0.42602662 -0.11205881  1.57583905 -0.21513109]
 [-0.6331516  -1.42771306 -1.67125322  0.38850975]] 



array([[ 2,  2, -2, -2],
       [ 2, -2, -2, -2],
       [ 2, -2,  2, -2],
       [-2, -2, -2,  2]])

In [16]:
# [연습문제] arr의 모든 양수를 2로 바꿔보자.
arr = np.random.randn(4,4)
print(arr,'\n')
np.where(arr>0,2,arr)
# 이 경우에는 아닌 경우를 지정하지 않았기 때문에 arr 그대로 둔다고 말해줘야 함

[[-0.89304106 -1.62862982  0.9303644   1.5130584 ]
 [-0.30797797  0.21122002 -0.96134789  0.04538075]
 [ 0.21252087 -1.11932921 -0.83830317  1.15195166]
 [-1.10791506  2.15858115  0.83753364 -0.66396382]] 



array([[-0.89304106, -1.62862982,  2.        ,  2.        ],
       [-0.30797797,  2.        , -0.96134789,  2.        ],
       [ 2.        , -1.11932921, -0.83830317,  2.        ],
       [-1.10791506,  2.        ,  2.        , -0.66396382]])

In [17]:
# meshgrid()
# 두 개의 1차원 배열을 받아서 가능한 모든 (x,y) 짝을 만드는 함수

x = np.arange(1,4)
y = np.arange(1,4)
xs,ys = np.meshgrid(x,y)
print(xs,'\n',ys)

[[1 2 3]
 [1 2 3]
 [1 2 3]] 
 [[1 1 1]
 [2 2 2]
 [3 3 3]]


In [18]:
# np.sort()
np.random.seed(0) # 랜덤 출력 고정
arr = np.random.randint(1,100,size = 10)
print(arr,'\n')
print(np.sort(arr)) # 기존 것은 놔두고 새로운 어레이 생성

[45 48 65 68 68 10 84 22 37 88] 

[10 22 37 45 48 65 68 68 84 88]


In [19]:
# 행렬이 2차원 이상일 때 axis 축 값 설정을 통해 행, 열 방향으로 정렬 수행
ar2d = np.array([[8,12],[17,1]])
ar2d_ax0 = np.sort(ar2d, axis=0)
ar2d_ax1 = np.sort(ar2d, axis=1)
print(ar2d,'\n',ar2d_ax0) # 행 방향으로 크기 작은 놈이 제일 상단으로 이동
print(ar2d,'\n',ar2d_ax1) # 열 방향으로 크기 작은 놈이 제일 상단으로 이동

[[ 8 12]
 [17  1]] 
 [[ 8  1]
 [17 12]]
[[ 8 12]
 [17  1]] 
 [[ 8 12]
 [ 1 17]]


In [20]:
# ndarray.sort(): 원본에 반영하여 정렬
np.random.seed(0) # 일단 고정해두고
arr = np.random.randint(1,10,size=10)
print(arr,'\n')
arr.sort() # np.sort(a)와는 다르다 이거야~
print(arr)

[6 1 4 4 8 4 6 3 5 8] 

[1 3 4 4 4 5 6 6 8 8]


In [21]:
# 다차원 배열의 정렬은 sort 메소드에 넘긴 축에 따라 1차원 부분을 정렬
# 뭔 말이냐 하면...
# 행, 열, 깊이 중 어느 방향으로 정렬할지 정한 후
# 해당 위치에서 행or열or깊이끼리 비교 후 정렬한다 이 얘기임
import numpy as np
np.random.seed(0)
arr = np.random.randint(1,28,size=(3,3,3))
print(arr,'\n')
arr.sort(2) # 0은 깊이, 1은 열, 2는 행
print(arr)

[[[13 16 22]
  [ 1  4  4]
  [ 8 10 20]]

 [[22 19  5]
  [24  7 25]
  [25 13 27]]

 [[ 2  7  8]
  [24 15 25]
  [18  6 26]]] 

[[[13 16 22]
  [ 1  4  4]
  [ 8 10 20]]

 [[ 5 19 22]
  [ 7 24 25]
  [13 25 27]]

 [[ 2  7  8]
  [15 24 25]
  [ 6 18 26]]]


In [22]:
# 정렬된 행렬의 인덱스 반환: 기존 원본 행렬의 원소에 대한 인덱스를 필요로 할 때
# 정렬은 했지만 얘 말구 원본의 인덱스를 요구할 때
# 그러면 argsort를 쓰고 출력 결과에서 원본의 인덱스를 확인 가능!

ar0 = np.array([3,1,9,5])
ar1 = np.argsort(ar0)
print(ar0,ar1,type(ar1))

[3 1 9 5] [1 0 3 2] <class 'numpy.ndarray'>


In [23]:
# 배열에서 정렬한 후 일정 비율(%) 분위수에 해당하는 요소만 추려내기
# 여기선 5%로 해보자

np.random.seed(0)
large = np.random.randn(1000)
large.sort()
large[int(0.05*len(large))] # len(large) 말고 1000으로 해도 되지 않나? 1천개를 만든 셈이니까

# large[]에서 []안의 자리에
# int(0.05*len(large)), int(0.05*1000),int(50),50
# 전부 동일한 결과 나왔음
# 어쨌든 원하는 분위의 값을 뽑으려면 해당 퍼센티지에 배열의 크기를 곱하라는 뜻인가 봄

-1.6326345262344952

In [61]:
# 배열 집합 연산
names = np.array(['Jade','Jade','Wednesday','Wendy','Wendy'])
print(np.unique(names)) # 이거 로또 만들 때 써봤다. set랑 같은 방식임
# print(sorted(set(list(names))))
sorted(set(names))

['Jade' 'Wednesday' 'Wendy']


['Jade', 'Wednesday', 'Wendy']

In [25]:
# np.in1d(): 첫 번째 배열의 원소가 두 번째 배열의 원소를 포함하는지 알려주는 불리언 배열을 반환
v1 = np.array([6,0,1,3,2,5,7])
v2 = np.array([2,3,6])
np.in1d(v1,v2)

array([ True, False, False,  True,  True, False, False])

In [26]:
# 배열 데이터의 입출력
# np.save, np.load는 바이너리 형식 .npy 파일로 저장

arr = np.arange(10)
np.save('some_array',arr)
np.load('some_array.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
# np.savez: 여러 개의 배열을 압축된 형식으로 저장
np.savez('array_archive.npz',a = arr, b = arr)
# arch = np.load('array_archive.npz')
# arch['a']
np.load('array_archive.npz')['a']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
# [연습문제] 인덱싱을 사용하여 [1 0 1 0 1 0 1 0 1 0]을 출력하세요.

a = np.ones(10).astype(int)
a[[1,3,5,7,9]] = 0
print(a)

[1 0 1 0 1 0 1 0 1 0]


In [29]:
# [연습문제] a = np.arange(10)에서 [6,7,8,9]처럼 출력하세요
a = np.arange(10)
print(a[a>5].tolist())

[6, 7, 8, 9]


In [30]:
# [연습문제] a에서 최대값, 최소값 출력
a = np.arange(1,11)
print(f'최댓값: {max(a)}\n최솟값: {min(a)}')

# [연습문제] a에서 최대값, 최소값의 인덱스도 출력해 보자.
print(f'최댓값: {np.argmax(a)}\n최솟값: {np.argmin(a)}')

최댓값: 10
최솟값: 1
최댓값: 9
최솟값: 0


In [31]:
# [연습문제] a에서 인덱스 배열을 역순으로 출력하세요.
# 인덱스는 arg 뭐시기를 쓰면 된다!
a = np.arange(10)
print(np.argsort(a)[::-1])

[9 8 7 6 5 4 3 2 1 0]


In [32]:
# [연습문제] np.ones((10,10))을 아래와 같이 출력하세요.
# array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
#        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
#        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
#        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
#        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
#        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
#        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
#        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
#        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
#        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

n1 = np.ones((10,10))
n1[1:9,1:9] = 0
n1

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

### [파이썬 Random 함수]

import random

In [33]:
# random 비교하기
import random

print(random.randint(1,11)) # a<=x<b의 랜덤한 정수
print(random.random()) # 0<=x<1의 랜덤한 실수
print(random.uniform(10,21)) # min<=x<max의 랜덤한 실수
print(random.randrange(10)) # 범위 내에서 랜덤한 정수
print(random.choice([1,2,3,4,5])) # 리스트 내부에서의 요소를 랜덤하게 선택
print(random.sample([1,2,3,4,5],3)) # 리스트 내부에서의 요소를 중복 없이 n개 선택
li = [1,2,3,4,5]
random.shuffle(li) # 리스트 요소를 랜덤하게 섞은 후 리턴.
print(li)

8
0.944365117142195
18.29072378505885
3
4
[3, 2, 1]
[4, 1, 2, 3, 5]


### [Numpy Random 함수]

- np.random.seed(): seed를 통한 난수 생성
- np.random.randint(): 균일분포의 정수 난수 1개 생성
- np.random.rand(): 0부터 1 사이의 균일분포에서 난수 매트릭스 배열 생성
- np.random.randn(): 가우시안 표준 정규분포에서 난수 매트릭스 배열 생성 (평균 0, 표준편차 1)
- np.random.shuffle(): 기존 데이터의 순서 바꾸기
- np.random.choice(): 기존 데이터에서 sampling (중복 있음)

In [34]:
# np.random.randint
print(np.random.randint(8)) # 0~a 범위 내에서 1개 출력
print(np.random.randint(1,10,2)) # a, b 범위 내에서 c개 출력
print(np.random.randint(10,size=10)) # 위의 거랑 작동 똑같이 함. 중복도 나옴.
print(np.random.randint(10,20,size=10))
print(np.random.randint(10,20,size=(3,5))) # 범위 내 난수를 3행 5열 배열로 뽑아서 줌

0
[7 4]
[6 9 5 1 9 3 3 9 7 8]
[14 17 18 19 14 11 15 10 13 16]
[[13 10 13 16 19]
 [15 11 17 13 14]
 [17 10 13 15 16]]


In [35]:
# np.random.rand - 균일분포란, 정해진 범위 내에서의 모든 확률이 동일한 분포를 의미
print(np.random.rand(6))
print(np.random.rand(3,5))

[0.41378022 0.68638023 0.29589198 0.30329192 0.35588915 0.81030208]
[[0.57759009 0.07527728 0.0782461  0.37128694 0.76659105]
 [0.68868343 0.70798235 0.76721007 0.28715271 0.54825628]
 [0.54335264 0.7396325  0.95687057 0.27798994 0.79328167]]


In [36]:
# np.random.randn - 표준 정규분포
print(np.random.randn(10000).mean())

0.0006617981841580971


In [37]:
#np.random.shuffle()
# 리턴이 있는 게 아니라 원본 자체를 변형시키는 명령이기 때문에 프린트 해도 안 나옴. del처럼.
li = np.arange(1,11)
np.random.shuffle(li)
li

array([ 9,  7, 10,  8,  5,  1,  3,  6,  4,  2])

In [38]:
# np.random.choice()
li = np.arange(1,11)
print(np.random.choice(li,5))
li

[7 6 2 9 4]


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [39]:
# np.unique()
a = np.array([11,11,3,3,2,2,2,7])
index,count=np.unique(a,return_counts=True)
print(index)
print(count) # 2가 3개, 3이 2개, 7이 1개, 11이 2개

[ 2  3  7 11]
[3 2 1 2]


In [40]:
# np.random.uniform()
np.random.uniform(1,5,10)

array([3.34788639, 3.21494158, 3.04452419, 3.62292019, 1.96033346,
       3.04096773, 3.92613391, 2.80776932, 3.48598895, 4.76950154])

In [41]:
# uniform 함수의 최솟값, 최댓값을 각각 0,1로 지정한 것과 같음
np.random.random_sample((2,3))

array([[0.02211583, 0.56552577, 0.48109331],
       [0.96158088, 0.3216367 , 0.97622829]])

In [42]:
# 배열을 데이터프레임으로 변환
import pandas as pd
ar = np.random.rand(4,8)
df = pd.DataFrame(ar)
print(type(df))
df

<class 'pandas.core.frame.DataFrame'>


0         1         2         3         4         5         6  \
0  0.993922  0.668933  0.660081  0.685133  0.896554  0.892838  0.706141   
1  0.723627  0.713488  0.962748  0.251920  0.497482  0.588401  0.890006   
2  0.980750  0.813481  0.623734  0.633366  0.123680  0.697265  0.813343   
3  0.622701  0.475417  0.767889  0.014817  0.050799  0.472953  0.634107   

          7  
0  0.904172  
1  0.535504  
2  0.371532  
3  0.073489

In [43]:
print(df[0])
print(type(df[0])) # 시리즈가 모여서 데이터프레임이 되었다.
# 시리즈는 열(column)이 없다!

0    0.993922
1    0.723627
2    0.980750
3    0.622701
Name: 0, dtype: float64
<class 'pandas.core.series.Series'>


In [44]:
col = ['id','gender','age','region','product','price','qty','time']
index = [np.arange(1,5)]
df = pd.DataFrame(ar,index,col) # ar 데이터에, index 행, col열을 넣어 데이터프레임 만들기
df

id    gender       age    region   product     price       qty  \
1  0.993922  0.668933  0.660081  0.685133  0.896554  0.892838  0.706141   
2  0.723627  0.713488  0.962748  0.251920  0.497482  0.588401  0.890006   
3  0.980750  0.813481  0.623734  0.633366  0.123680  0.697265  0.813343   
4  0.622701  0.475417  0.767889  0.014817  0.050799  0.472953  0.634107   

       time  
1  0.904172  
2  0.535504  
3  0.371532  
4  0.073489

In [45]:
# [연습문제] id, gender, age 컬럼에 대하여
# 의미있는 값으로 변환하여 3개의 컬럼으로 구성된 데이터프레임을 출력하라.
ID = np.random.randint(1000,10000,3)
gen = np.random.choice(['M','F'],3)
age = np.random.randint(10,40,3)

data = np.array([ID,gen,age]).reshape(3,3).transpose()
df=pd.DataFrame(data,np.arange(1,4),['ID','Gender','Age'])
df

ID Gender Age
1  5524      M  12
2  7253      M  12
3  5123      M  32

In [46]:
import pandas as pd
ar = np.zeros((4,3))
columns = ['id','gender','age']
index = [np.arange(4)]
df = pd.DataFrame(ar,index,columns=columns)
# df.id = np.array([1,2,3,4])
df.id = np.arange(1,5)
# df.gender = np.array([0,1,0,1])
np.random.seed(0)
df.gender = np.random.randint(2,size=4)
# df.age = np.array([20,30,40,50])
df.age = np.arange(1,5) * 10
df

id  gender  age
0   1       0   10
1   2       1   20
2   3       1   30
3   4       0   40

In [47]:
# [과제] 아래 배열에서 3차원과 2차원을 변경하여 출력하세요.
# (완료 후 shape 확인)
arr = np.arange(16).reshape(2,2,4)
arrt = np.transpose(arr,(1,0,2))
print(arr,arr.shape,'\n')
print(arrt,arrt.shape)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]] (2, 2, 4) 

[[[ 0  1  2  3]
  [ 8  9 10 11]]

 [[ 4  5  6  7]
  [12 13 14 15]]] (2, 2, 4)


In [48]:
# [과제] 상기 과제의 arr에서 2차원과 1차원을 변경하여 출력하세요.
arr = np.arange(16).reshape(2,2,4)
arrt = np.transpose(arr,(0,2,1))
print(arr,arr.shape,'\n')
print(arrt,arrt.shape)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]] (2, 2, 4) 

[[[ 0  4]
  [ 1  5]
  [ 2  6]
  [ 3  7]]

 [[ 8 12]
  [ 9 13]
  [10 14]
  [11 15]]] (2, 4, 2)


In [49]:
# [과제] np.ones((5,5))를 아래와 같이 출력하세요.
# array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
#        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
#        [0., 0., 1., 1., 1., 1., 1., 0., 0.],
#        [0., 0., 1., 1., 1., 1., 1., 0., 0.],
#        [0., 0., 1., 1., 1., 1., 1., 0., 0.],
#        [0., 0., 1., 1., 1., 1., 1., 0., 0.],
#        [0., 0., 1., 1., 1., 1., 1., 0., 0.],
#        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
#        [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

# append
n1 = np.ones((5,5))
n10 = np.zeros((2,5))
n01 = np.zeros((9,2))
n = np.append(n10,n1,axis=0)
n = np.append(n,n10,axis=0)
n = np.append(n01,n,axis=1)
n = np.append(n,n01,axis=1)
print(n)

# indexing
n1 = np.ones((5,5))
n2 = np.zeros((9,9))
n2[2:7,2:7] = n1
print(n2)


[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [50]:
# pad 합수 쓰면 알아서 잘 포장해 줌
arr1 = np.ones((5,5))
np.pad(arr1,(2,2),'constant',constant_values=0)


array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [51]:
# [과제] np.zeros((8,8))을 이용해서 아래와 같이 출력하세요.
# 2가지 방식: 인덱싱, tile 함수
# array([[0, 1, 0, 1, 0, 1, 0, 1],
#        [1, 0, 1, 0, 1, 0, 1, 0],
#        [0, 1, 0, 1, 0, 1, 0, 1],
#        [1, 0, 1, 0, 1, 0, 1, 0],
#        [0, 1, 0, 1, 0, 1, 0, 1],
#        [1, 0, 1, 0, 1, 0, 1, 0],
#        [0, 1, 0, 1, 0, 1, 0, 1],
#        [1, 0, 1, 0, 1, 0, 1, 0]])

# 인덱싱
a = np.zeros((8,8))
a[[0,2,4,6]] = [0,1,0,1,0,1,0,1]
a[[1,3,5,7]] = [1,0,1,0,1,0,1,0]
print(a)

# tile함수
a0 = np.tile([[0,1]],4)
a1 = np.tile([[1,0]],4)
aa = np.zeros((8,8))
for i in range(8):
    if i%2==0: aa[[i]]+=a0
    else: aa[[i]]+=a1
print(aa)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]
[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [52]:
a = np.zeros(8)
b = np.tile([1,0],4)
a[:] = b
a

array([1., 0., 1., 0., 1., 0., 1., 0.])

In [53]:
# 수정 보완해서 다시 해보자
# 관측치는 1천, 코드가 같을 때에 단가가 같게 처리
# 워닝 사인 삭제

# [과제] 아래 가이드에 따라 고객 구매데이터를 생성하고
# ID, 성별, 연령, 지역, 상품, 가격, 구매시간
# 데이터프레임으로 변환하여 출력하세요.

# ID: 1~1000번 일련번호
# gender: 0,1 정수 난수 생성
# age: 0~80 사이 정수 난수 생성
# region: 1~10 사이 정수 난수 생성
# product_19: 제품코드 100~200
# product_20: 제품코드 100~200
# price_19: 1000~50000 사이의 실수 난수 생성
# price_20: 1000~50000 사이의 실수 난수 생성
# quantity_19: 1~100사이 정수 난수 생성
# quantity_20: 1~100사이 정수 난수 생성
# time_19: 01~24 사이 정수 난수 생성
# time_20: 01~24 사이 정수 난수 생성
# amount_19: price_19*quantity_19
# amount_20: price_20*quantity_20
# sales: 19년 대비 20년 구매금액이 증가 상태면 1, 감소면 0

# amount_20-amount_19>0 이면 트루, 아니면 false로 해볼까?

import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

arr = np.zeros((1000,15))
col = ['ID','Gender','Age','Region','Product_19','Product_20','Price_19','Price_20',
       'Quantity_19','Quantity_20','Time_19','Time_20','Amount_19','Amount_20','Sales']
index = np.arange(1,1001)
df = pd.DataFrame(arr,index,col)

p19 = np.random.randint(1,500,size=1000)*100
q19 = np.random.randint(1,101,size=1000)
p20 = np.random.randint(1,500,size=1000)*100
q20 = np.random.randint(1,101,size=1000)

df.ID = np.random.randint(1,1001,size=1000)
df.Gender = np.random.randint(2,size=1000)
df.Age = np.random.randint(80,size=1000)
df.Region = np.random.randint(1,11,size=1000)
df.Product_19 = np.random.randint(100,201,size=1000)
df.Product_20 = np.random.randint(100,201,size=1000)
df.Price_19 = p19
df.Price_20 = p20
df.Quantity_19 = q19
df.Quantity_20 = q20
#if df.Product_19==df.Product_20:
#    p19 = p20


df.Time_19 = np.random.randint(1,25,size=1000)
df.Time_20 = np.random.randint(1,25,size=1000)
# 시간 출력시 앞에 0 채우기(zfill)

df.Amount_19 = p19*q19
df.Amount_20 = p20*q20
df.Sales = np.where(df.Amount_20-df.Amount_19>0,1,0)

df

# if df.Product_19==df.Product_20:
#    p19 = p20

ID  Gender  Age  Region  Product_19  Product_20  Price_19  Price_20  \
1      11       0   32       7         172         196     32400     36000   
2     307       0   64       5         147         160     25200     25600   
3     990       1   76       6         159         133     19600     21100   
4     724       0   16       7         156         151     36000      7300   
5     803       0   75       1         179         118      1000     25600   
...   ...     ...  ...     ...         ...         ...       ...       ...   
996   646       1   20       9         119         199      5100     13500   
997   934       0   49       7         166         174     24300     12100   
998   901       1    8       3         156         125     35900     13100   
999   765       0   64       8         123         105      2100     15500   
1000  768       0   34       2         117         105     17200     23900   

      Quantity_19  Quantity_20  Time_19  Time_20  Amount_19  Amount_20  Sales  
1               1           26        5       19      32400     936000      1  
2              67           14        4       21    1688400     358400      0  
3              98           64       12        1    1920800    1350400      0  
4              13           92        9       14     468000     671600      1  
5              16           63        1        8      16000    1612800      1  
...           ...          ...      ...      ...        ...        ...    ...  
996            30            5       24        2     153000      67500      0  
997            10            5        6        3     243000      60500      0  
998            12           19       11        9     430800     248900      0  
999           100           70        4        2     210000    1085000      1  
1000           27           15       22       15     464400     358500      0  

[1000 rows x 15 columns]

In [54]:
import string
import warnings
warnings.filterwarnings('ignore')

arr = np.zeros((1000,15))
columns = ['id','gender','age','region','product_19','product_20','price_19','price_20','quantity_19','quantity_20','time_19','time_20','amount_19','amount_20','sales']
index = [np.arange(1000)]
df = pd.DataFrame(arr,index,columns = columns)

id_arr = np.arange(1,1001) ; np.random.shuffle(id_arr) ; df.id = id_arr
gender_ar = np.array(['남','여']) ; df.gender = np.array(np.random.choice(gender_ar) for _ in range(1000))
df.age = np.random.randint(80,size = 1000)
df.region = np.random.randint(10,size = 1000)
def code(a):
    li = []
    for _ in range(a):
        result = ""
        for _ in range(2):
            result += random.choice(string.ascii_uppercase)
        for _ in range(3):
            result += random.choice(string.digits)
        li.append(result)
    return np.array(li)
df.product_19 = code(1000)
df.product_20 = code(1000)
df.price_19 = np.random.rand(1000)*499000+1000
df.price_20 = np.random.rand(1000)*499000+1000
df.quantity_19 = np.random.randint(1,101,size=1000)
df.quantity_20 = np.random.randint(1,101,size=1000)
time_ar = []
for _ in range(1,25):                   # df.time_19 = np.random.randint(1,25,size=1000).astype(str)       # 이 방식 안돼..
    time_ar.append(f'{_}'.zfill(2))     # df.time_19 = df.time_19.str.zfill(2)
np.array(time_ar)
df.time_19 = np.array(np.random.choice(time_ar) for _ in range(1000))
df.time_20 = np.array(np.random.choice(time_ar) for _ in range(1000))
# df.time_19 = np.random.randint(1,25,size=1000)
# df.time_20 = np.random.randint(1,25,size=1000)
df.amount_19 = df.price_19 * df.quantity_19
df.amount_20 = df.price_20 * df.quantity_20
for _ in range(1000):
    if df.amount_19[_] <= df.amount_20[_]:
        df.sales[_] = 1
    else:
        df.sales[_] = 0
#pd.Series(df.sales).astype(int)
pd.options.display.float_format = '{:.2f}'.format
df

id gender  age  region product_19 product_20  price_19  price_20  \
0    126      남   41       0      VR968      DH631 459621.07 138374.37   
1     25      남   79       8      TQ406      FW442 296461.52  80912.00   
2    810      여   51       1      QH806      XI203 107010.84 392979.25   
3    634      여   20       3      KN797      ZK196 208804.01 206969.42   
4    676      여   71       1      AH672      TG552 232884.13 304181.10   
..   ...    ...  ...     ...        ...        ...       ...       ...   
995  576      남    3       9      PW764      WT864 209575.73  98040.55   
996  988      남   15       1      YU712      ED899 384661.27 154883.36   
997  454      여   79       8      WS218      YC238 240932.95 116774.93   
998  100      여    0       1      FW286      IW026  97385.62  16132.33   
999  665      여   32       2      PT443      VK787 165946.13 241478.03   

     quantity_19  quantity_20 time_19 time_20   amount_19   amount_20  sales  
0             73           82      07      13 33552338.35 11346698.74   0.00  
1             38           19      05      14 11265537.81  1537328.08   0.00  
2             85           94      14      02  9095921.48 36940049.79   1.00  
3             18           67      04      03  3758472.11 13866951.19   1.00  
4             19           21      02      20  4424798.43  6387803.08   1.00  
..           ...          ...     ...     ...         ...         ...    ...  
995           31           96      22      24  6496847.70  9411892.68   1.00  
996           91           93      06      24 35004175.60 14404152.25   0.00  
997           46            8      21      01 11082915.65   934199.42   0.00  
998           24           94      24      01  2337254.81  1516439.11   0.00  
999           98           14      18      03 16262720.98  3380692.35   0.00  

[1000 rows x 15 columns]

In [55]:
import numpy as np
import pandas as pd

customer = 1000

array = np.zeros((customer,14),dtype = int)
df = pd.DataFrame(array,(np.arange(1,customer+1)),columns = ['id','gender','age','product_19','product_20','price_19','price_20','quantity_19','quantity_20','time_19','time_20','amount_19','amount_20','sales'])
np.random.seed(0)
df.id = np.arange(1,customer+1)
df.gender = np.random.choice(['M','F'],customer)
df.age = np.random.randint(1,81,size=customer)
df.product_19 = np.random.randint(11111,100000,size = customer)
df.product_20 = np.random.randint(11111,100000,size = customer)

pricearray= np.random.randint(10,500,size = 100000)*100

for i in range(1,customer+1):
    df.price_19[i] = pricearray[df.product_19[i]]
    df.price_20[i] = pricearray[df.product_20[i]]

df.quantity_19 = np.random.randint(1,101,size = customer)
df.quantity_20 = np.random.randint(1,101,size = customer)

df.time_19 = np.random.randint(1,25,size = customer)
df.time_20 = np.random.randint(1,25,size = customer)

df.amount_19 = df.price_19*df.quantity_19
df.amount_20 = df.price_20*df.quantity_20

for i in range(1,customer+1):
    if df.amount_20[i]>df.amount_19[i]:
        df.sales[i] = 1
    else:
        df.sales[i] = 0

df

id gender  age  product_19  product_20  price_19  price_20  \
1        1      M   40       24227       55976     42900     17000   
2        2      F   29       77462       78920     27400     38500   
3        3      F   25       53750       46507     25600     49500   
4        4      M   19       73611       29381     28000     19100   
5        5      F   68       82728       84075      1300     23200   
...    ...    ...  ...         ...         ...       ...       ...   
996    996      M   24       73435       97517      6400     21300   
997    997      M   53       36781       83820     34400     21600   
998    998      M   24       38495       96299     12700      7700   
999    999      F   73       56675       61737     15700     21000   
1000  1000      M   42       88153       76382     10100     32500   

      quantity_19  quantity_20  time_19  time_20  amount_19  amount_20  sales  
1              76           79       18       20    3260400    1343000      0  
2              66           45        4       19    1808400    1732500      0  
3              55           36       24       18    1408000    1782000      1  
4              71           15        2       17    1988000     286500      0  
5              20           90        3       20      26000    2088000      1  
...           ...          ...      ...      ...        ...        ...    ...  
996             7           76       20       10      44800    1618800      1  
997            28           53       10       24     963200    1144800      1  
998            72           35        8        7     914400     269500      0  
999            54            6        1       17     847800     126000      0  
1000           56           39       13       23     565600    1267500      1  

[1000 rows x 14 columns]

In [56]:
# [도전과제] np.arange(4)를 이용해서 아래와 같이 출력하세요.
# array([[0, 0, 0, 0, 0],
#        [1, 0, 0, 0, 0],
#        [0, 2, 0, 0, 0],
#        [0, 0, 3, 0, 0],
#        [0, 0, 0, 4, 0]])

a = np.arange(4)
a0 = np.zeros((4,4))
a0[[0,1,2,3],[0,1,2,3]] = a+1
a0 = np.append(np.append(np.zeros((1,4)),a0,axis=0),np.zeros((5,1)),axis=1)
a0

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [0., 0., 3., 0., 0.],
       [0., 0., 0., 4., 0.]])

In [57]:
zero = np.zeros((5, 5))
a = np.arange(4)

for i in range(4):
    zero[i + 1, i] = a[i] + 1
    
print(zero)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


In [58]:
# diag 함수
d = np.diag(np.arange(4)+1,k=-1)
d

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [59]:
# [도전과제] np.arange(336).reshape(6,7,8)에서 100번째 요소의 인덱스를 구하세요.
import numpy as np
print(np.arange(336)[99])
# 100번째(인덱스 99) 요소값은 99
np.where(np.arange(336).reshape(6,7,8)==99)

99


(array([1], dtype=int64), array([5], dtype=int64), array([3], dtype=int64))

In [60]:
# unravel을 써보자!
arr = np.arange(336).reshape(6,7,8)
#print(arr)
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)
