In [1]:
import numpy as np
import pandas as pd

In [51]:
# [과제] zeros_like, ones_like, full_like 함수를 예시로 하나씩만 만들어 보자.
a = np.arange(1,21).reshape(4,5)
a0 = np.zeros_like(a)
a1 = np.ones_like(a)
af = np.full_like(a,5)
display(a,a0,a1,af)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [9]:
# [과제] 1 ~ 100까지 정수에서 3의 배수인 것만을 출력(for문과 배열 두가지 방식)
a = np.arange(1,101)
l1=[]
for i in a:
    if i%3==0:
        l1.append(i)
print(l1)
a1 = np.arange(3,100,3)
print(a1)
# 또는 a를 이용하여
a[a%3==0] # 이거슨 불린인덱싱

[3, 6, 9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99]
[ 3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69 72
 75 78 81 84 87 90 93 96 99]


array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51,
       54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [11]:
# [과제] 1 ~ 100까지 정수에서 5의 배수이면서 2의 배수인 것만을 출력(for문과 배열 두가지 방식)
a = np.arange(1,101)
for i in a:
    if i%10==0:
        print(i,end=" ")
a[a%10==0]

10 20 30 40 50 60 70 80 90 100 

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [12]:
# [과제] 표준정규분포로 구성된 5행 5열 다차원 배열을 생성하고 함수를 이용하여 평균과 표준편차를 구하세요.
a = np.random.randn(5,5)  # 가우시안 표준 정규분포의 특징은
display(a.mean(),a.std()) # 요소가 많을수록 평균이 0, 표준편차가 1에 수렴 

0.09987654500743236

0.9574348503334579

In [13]:
# [과제] zeros 함수를 이용해서 아래와 같이 출력하세요.
# array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])
a = np.zeros(10)
a[4]=1
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [14]:
# [과제] 인덱싱을 이용하여 아래 배열을 내림차순으로 정렬하세요.
# [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
a = np.arange(10)
a[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [15]:
# [과제] [1,2,0,0,4,0]에서 zero가 아닌 인덱스를 배열 형태로 출력하세요.
a = [1,2,0,0,4,0]
np.nonzero(a)

(array([0, 1, 4], dtype=int64),)

In [25]:
# [연습문제] id, gender, age 컬럼에 대하여
# 의미있는 값으로 변환하여 3개의 컬럼으로 구성된 데이터프레임을 출력하라.

ID = pd.Series(np.arange(1,11))
gender = pd.Series(np.random.choice(['F','M'],10))
age = pd.Series(np.random.randint(10,59,10))

df = pd.DataFrame([ID,gender,age]).T
df.columns=['ID','Gender','Age']
df.set_index('ID',inplace=True)
df

Gender Age
ID           
1       F  13
2       F  51
3       F  10
4       M  38
5       F  55
6       M  14
7       M  18
8       F  40
9       F  27
10      M  52

In [29]:
# [과제] 아래 배열에서 3차원과 2차원을 변경하여 출력하세요.
# (완료 후 shape 확인)
arr = np.arange(16).reshape(2,2,4)
ar = np.transpose(arr,(1,0,2))
print(ar,ar.shape)

[[[ 0  1  2  3]
  [ 8  9 10 11]]

 [[ 4  5  6  7]
  [12 13 14 15]]] (2, 2, 4)


In [31]:
# [과제] 상기 과제의 arr에서 2차원과 1차원을 변경하여 출력하세요.
arr = np.arange(16).reshape(2,2,4)
ar = np.transpose(arr,(0,2,1))
print(ar,ar.shape)

[[[ 0  4]
  [ 1  5]
  [ 2  6]
  [ 3  7]]

 [[ 8 12]
  [ 9 13]
  [10 14]
  [11 15]]] (2, 4, 2)


In [37]:
# [과제] np.ones((5,5))를 아래와 같이 출력하세요.
# array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
#        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
#        [0., 0., 1., 1., 1., 1., 1., 0., 0.],
#        [0., 0., 1., 1., 1., 1., 1., 0., 0.],
#        [0., 0., 1., 1., 1., 1., 1., 0., 0.],
#        [0., 0., 1., 1., 1., 1., 1., 0., 0.],
#        [0., 0., 1., 1., 1., 1., 1., 0., 0.],
#        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
#        [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

a = np.ones((5,5))
a0 = np.pad(a,(2,2),'constant',constant_values=0)
a0

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [42]:
# [과제] np.zeros((8,8))을 이용해서 아래와 같이 출력하세요.
# 2가지 방식: 인덱싱, tile 함수
# array([[0, 1, 0, 1, 0, 1, 0, 1],
#        [1, 0, 1, 0, 1, 0, 1, 0],
#        [0, 1, 0, 1, 0, 1, 0, 1],
#        [1, 0, 1, 0, 1, 0, 1, 0],
#        [0, 1, 0, 1, 0, 1, 0, 1],
#        [1, 0, 1, 0, 1, 0, 1, 0],
#        [0, 1, 0, 1, 0, 1, 0, 1],
#        [1, 0, 1, 0, 1, 0, 1, 0]])

a = np.zeros((8,8))
b = np.tile([0,1],4)
c = np.tile([1,0],4)
a[[0,2,4,6]] = b
a[[1,3,5,7]] = c
a

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

In [46]:
# [도전과제] np.arange(4)를 이용해서 아래와 같이 출력하세요.
# array([[0, 0, 0, 0, 0],
#        [1, 0, 0, 0, 0],
#        [0, 2, 0, 0, 0],
#        [0, 0, 3, 0, 0],
#        [0, 0, 0, 4, 0]])

a = np.eye(4,4)
b = np.arange(1,5)
a = a*b
a = np.append(np.zeros((1,4)),a,axis=0)
a = np.append(a,np.zeros((5,1)),axis=1)
a

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [0., 0., 3., 0., 0.],
       [0., 0., 0., 4., 0.]])

In [50]:
# [도전과제] np.arange(336).reshape(6,7,8)에서 100번째 요소의 인덱스를 구하세요.
a = np.arange(336).reshape(6,7,-1)
np.where(a==99)

(array([1], dtype=int64), array([5], dtype=int64), array([3], dtype=int64))

In [59]:
# [연습문제] 1~100을 아래와 같이 출력해 보세요
#[[  1   2   3   4   5   6   7   8   9  10]
# [ 20  19  18  17  16  15  14  13  12  11]
# [ 21  22  23  24  25  26  27  28  29  30]
# [ 40  39  38  37  36  35  34  33  32  31]
# [ 41  42  43  44  45  46  47  48  49  50]
# [ 60  59  58  57  56  55  54  53  52  51]
# [ 61  62  63  64  65  66  67  68  69  70]
# [ 80  79  78  77  76  75  74  73  72  71]
# [ 81  82  83  84  85  86  87  88  89  90]
# [100  99  98  97  96  95  94  93  92  91]] <class 'numpy.ndarray'>

a = np.arange(1,101).reshape(10,-1)
a[[1,3,5,7,9]]=a[[1,3,5,7,9],::-1]
a

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 20,  19,  18,  17,  16,  15,  14,  13,  12,  11],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 40,  39,  38,  37,  36,  35,  34,  33,  32,  31],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 60,  59,  58,  57,  56,  55,  54,  53,  52,  51],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 80,  79,  78,  77,  76,  75,  74,  73,  72,  71],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [100,  99,  98,  97,  96,  95,  94,  93,  92,  91]])

In [69]:
# [연습문제] arr의 모든 양수를 2로 바꿔보자.
arr = np.random.randn(4,4)
np.where(arr>0,2,arr)

array([[ 2.        , -0.17184081, -1.50639955, -0.50034691],
       [-0.67990045,  2.        ,  2.        , -1.43837135],
       [-0.14632677,  2.        , -0.09876695,  2.        ],
       [-0.69429111,  2.        , -1.60987775, -0.85351637]])

In [71]:
# [연습문제] 인덱싱을 사용하여 [1 0 1 0 1 0 1 0 1 0]을 출력하세요.
a = np.ones(10)
a[[1,3,5,7,9]] = 0
a

array([1., 0., 1., 0., 1., 0., 1., 0., 1., 0.])

In [86]:
# [연습문제] a = np.arange(10)에서 [6,7,8,9]처럼 출력하세요
# [연습문제] a에서 최대값, 최소값 출력
# [연습문제] a에서 최대값, 최소값의 인덱스도 출력해 보자.
# [연습문제] a에서 인덱스 배열을 역순으로 출력하세요.
a = np.array([1,5,2,6,4,7,3,9,8])
display(a[6:], a.max(),a.min(),np.argmax(a),np.argmin(a),np.argsort(a[::-1]))

array([3, 9, 8])

9

1

7

0

array([8, 6, 2, 4, 7, 5, 3, 0, 1], dtype=int64)

array([8, 9, 3, 7, 4, 6, 2, 5, 1])

In [104]:
# [연습문제] np.ones((10,10))을 아래와 같이 출력하세요.
# array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
#        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
#        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
#        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
#        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
#        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
#        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
#        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
#        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
#        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])
a = np.ones((10,10))
a[1:9,1:9] = np.zeros((8,8))
a

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [105]:
# [연습문제] 정수와 실수로 구성된 list_e = [1.2,2.3,3]을
# numpy를 이용하여 실수형과 정수형으로 각각 출력하세요.
list_e = [1.2,2.3,3]
e = np.array(list_e)
display(e.astype(int),e.astype(float))

array([1, 2, 3])

array([1.2, 2.3, 3. ])

In [111]:
# [연습문제] 2차원 배열 ar2d에서 [3,6],[[1,2],[4,5]]를 각각 출력하세요.
# [연습문제] 2차원 배열 ar2d를 다른 방식으로 아래와 같이 출력하세요.
# [[1,2,3]
#  [4,5,6]]
ar2d = np.arange(1,10).reshape(3,-1)
display(ar2d[0:2,2],ar2d[0:2,0:2],ar2d[0:2,:])

array([3, 6])

array([[1, 2],
       [4, 5]])

array([[1, 2, 3],
       [4, 5, 6]])

In [112]:
# [연습문제] ar1d에서 일반 인덱스와 불린을 이용해 각각 [6,7,8,9]를 출력해 보세요.
ar1d = np.arange(1,10)
display(ar1d[5:],ar1d[ar1d>5])

array([6, 7, 8, 9])

array([6, 7, 8, 9])

In [113]:
# [연습문제] 1~14까지의 ndarray를 만들어 array_e로 저장하고
# (array_e/2)>5를 만족하는 값을 불린 인덱싱으로 출력
array_e = np.arange(1,15)
array_e[array_e/2 >5]

array([11, 12, 13, 14])