https://codedrive.tistory.com/91 <br>
내장함수는 임포트 필요 없음. 바로 쓰면 됨<br>
외장함수는 임포트 해서 쓸 수 있고, 별도의 프로그램이나 라이브러리는 설치 후 임포트 해야 함<br>

In [6]:
# 2와 5를 더한 후 3으로 나눈 나머지 값을 사용자 함수를 이용하여 구하세요.
# definition으로 함수를 선언, 변수가 몇 개 들어가는지도 언급해 주기
# 주어진 기능을 수행 후 결과를 리턴해 주는 기능도 반드시 넣어야 함

def cal_abc(a,b,c):
    return(a+b)%c

cal_abc(2,5,3)

1

In [13]:
# strip 스트립
# 문자열 앞뒤의 공백을 제거하고 아래와 같이 출력하세요.
# 깨끗하게 다듬는다는 뜻임

input_a = """
                       It is true
'Python is fit for data analysis'                       
                      """

print(input_a.strip())

It is true
'Python is fit for data analysis'


In [9]:
# split 스플릿
# "10/20/30/40/50"을 '/'을 기준으로 자르세요.
# 조건을 기준으로 나눈 후 리스트화

a = '10/20/30/40/50'
a.split('/')

['10', '20', '30', '40', '50']

Python random 모듈

https://nittaku.tistory.com/443

In [2]:
import numpy as np
np.random.seed(0) # 이렇게 seed를 넣으면 결과가 고정됨
num = np.random.randint(5,size=10) # 10개의 숫자를 5 안의 범위 내에서 뽑는다는 말
num

array([4, 0, 3, 3, 3, 1, 3, 2, 4, 0])

In [1]:
# 짝수와 짝수를 입력하면 곱한 값을 출력하고 홀수와 홀수를 입력하면 덧셈 값을 출력
# 그 외에는 다시 입력하는 메시지를 내보내는 프로그램

def even(a,b):
    return(a*b)

def odd(a,b):
    return(a+b)

while 1:
    
    n1 = int(input('첫 번째 숫자를 입력해 주세요. '))
    n2 = int(input('두 번째 숫자를 입력해 주세요. '))

    if n1==0 or n2==0:
        print('다른 숫자를 입력해 주세요.')
    elif n1%2==0 and n2%2==0:
        print(even(n1,n2))
        break
    elif n1%2==1 and n2%2==1:
        print(odd(n1,n2))
        break
    else: print('다른 숫자를 입력해 주세요.')

첫 번째 숫자를 입력해 주세요. 1
두 번째 숫자를 입력해 주세요. 3
4


In [77]:
# [과제] 1부터 100까지 아래와 같이 2개의 수를 곱해서 가장 큰 수를 구하세요.
# 1*99, 2*98,..., 99*1

Max = 0
for i in range(1,100):
    a = i*(100-i)
    if a > Max:
        Max=a
print(Max)


2500


In [3]:
maximum = 0

for i in range(1,100):
    if i*(100-i)>maximum:
        maximum=i*(100-i)
        
print(maximum)

# 이게 내가 한 거임

2500


In [6]:
# 이건 while문을 사용한 누군가의 풀이

n = 1
result = 0
while n<100:
    a = n*(100-n)
    if a>result:
        result = a
        n+=1
    else:
        n+=1
        continue
print(result)

2500


In [8]:
# 이건 zip 함수를 사용한 누군가의 풀이

def findBiggestOne():
    biggestNum = 0
    for i,j in zip(range(1,100), range(99,0,-1)):
        if i*j >biggestNum:
            biggestNum = i*j
    return biggestNum
print(findBiggestOne())

# zip 함수에서 지금 앞쪽은 1~100으로 오름차순 집합, 뒤쪽은 99~0까지 내림차순 집합


2500


In [1]:
# [과제] [    ]을 채워서 아래의 출력과 같이 출력하세요
# 출력:
# [[1,4,6],[2,5,8],[3,6,9]]

numbers = [1,2,3,4,5,6,7,8,9]
output = [[],[],[]]

for number in numbers:
    output[number%3-1].append(number) # 여기서 알고자 하는 건 리스트의 인덱스 안에 수식을 집어넣을 수 있다는 것
print(output)

#print(numbers[::3], numbers[1::3], numbers[2::3]) 이건 걍 모양새 보려는 코드

# (3으로 나눴을 때의 나머지 -1)이 인덱스 넘버이고, 인덱스 넘버는 0부터 시작하거든
# 1, 4, 7을 0번째 인덱스에 넣으려면 해당 숫자를 3으로 나눴을 때 0이 나오는 수식이 좋겠지?
# 같은 방식으로 2, 5, 8이 1번째 인덱스에 들어가야 하니 나머지에서 1을 빼주는 거야. 나머지는 2이니까.

[[1, 4, 7], [2, 5, 8], [3, 6, 9]]


In [10]:
# [과제] 사용자가 입력한 게임 회수만큼 로또 번호를 출력하는 프로그램을 작성하세요.
# 입력받은 횟수 만큼 중복 없는 난수 생성, 그런데 회차 내에서만 중복 없게끔
# 중복이 없는 건 세트지? 근데 총 숫자는 6개가 나와야 해.
# 세트로는 못 하겠어서 np 중에 중복 없애는 걸로 사용했음

import numpy as np

charge = int(input('이번엔 뜬다! 로또머신을 몇 회 가동할까요? >>> '))
for i in range(charge):
    while 1:
        num = np.random.randint(1,45,size=6)
        if len(np.unique(num)) <= 5:
            continue
        else:
            print(np.sort(num))
            break
            
# 세트 넣으면 중복 뜰 때 숫자가 없어져버림 ㅋㅋ 그렇다고 중복을 어케 빼는가.,.
# for 문으로 지정된 회차만큼, while문을 이용해 중복은 새로 돌리는 식으로 해결함


# 현재 m3 하는 중인데
# 이제야 하는 말이지만 np.random.choice 이용해서
# 1,45까지의 배열에서 6개 비복원으로 뽑기만 하면 되는 거였음
# 아는 만큼 보인다는 건 이런 거겠죠...?
a = np.arange(1,46)
display(sorted(np.random.choice(a,6)))

이번엔 뜬다! 로또머신을 몇 회 가동할까요? >>> 3
[11 14 15 21 31 36]
[11 16 24 29 37 39]
[ 3 23 24 28 34 35]


[1, 2, 20, 24, 28, 31]

In [1]:
#[연습문제] 발표할 인원을 입력하면 랜덤으로 발표자를 리스트로 출력해 주는 프로그램을 작성하세요.
# (중복 허용 X)

import random

name = ['야스오','가렌','진','녹턴','샤코','소라카','룰루',
        '제드','쉔','티모','마스터이','릴리아','니코','리 신','피오라']
while 1:
    try:
        num = int(input('발표할 인원 수를 입력하세요. >> '))
        if num>15 or num<1:
            raise ArithmeticError
    except ValueError:
        print('※ 숫자 형태의 번호만 입력 가능합니다.')
    except:
        print('※ 1에서 15 사이의 번호를 입력해 주세요.')
    else:
        print(random.sample(name,num))
        break

발표할 인원 수를 입력하세요. >> 3
['야스오', '룰루', '가렌']


In [6]:
# 선생님 풀이

name = ['야스오','가렌','진','녹턴','샤코','소라카','룰루',
        '제드','쉔','티모','마스터이','릴리아','니코','리 신','피오라']

li=[]
num = int(input('발표인원 입력 >> '))

for _ in range(num):
    p = random.randint(0,16)
    while p in li:
        p = random.randint(0,16) # 이미 리스트에 있다면 다시 돌리기. 근데 여러번 다시 돌리게 되긴 함
    li.append(name[p])
li

발표인원 입력 >> 3


['룰루', '리 신', '마스터이']

In [15]:
# 선생님 풀이 (중복을 피하는 방법)

from random import shuffle
from time import sleep

gnum = int(input('로또 횟수를 입력하세요. >>> '))

for i in range(gnum):
    li = [x+1 for x in range(45)] # x는 0~44니까 결과값(x+1)은 1~45가 나오지
    ret = []
    for j in range(6):
        shuffle(li)
        num = li.pop() # pop 함수는 뽑고나면 그 요소는 리스트에서 없어짐
        ret.append(num) # pop 함수에서 뽑은 요소를 저 빈 ret 리스트에 채우기
        ret.sort()
    print('로또 번호 %d: ' %(i+1), end="")
    print(ret)
    sleep(0.7) # 이건 걍 긴장감 증대를 위한 지연 입력

로또 횟수를 입력하세요. >>> 3
로또 번호 1: [3, 17, 22, 24, 32, 36]
로또 번호 2: [5, 7, 13, 24, 26, 27]
로또 번호 3: [2, 5, 27, 29, 31, 42]


In [16]:
# [과제] 남녀 파트너 정해주기 프로그램을 작성하세요 (5개 커플)

import random

male = ['김남','이남','박남','최남','정남']
female = ['김녀','이녀','박녀','최녀','정녀']

random.shuffle(male)
random.shuffle(female)
couple = zip(male,female)

for i, couple in enumerate(couple):
    print(f'{i+1}번째 짝: {couple[0]}과 {couple[1]}')

1번째 짝: 박남과 박녀
2번째 짝: 김남과 김녀
3번째 짝: 이남과 이녀
4번째 짝: 최남과 정녀
5번째 짝: 정남과 최녀


In [16]:
# for문을 사용해 셔플 돌린 집합에서 첫 번째 요소를 빼내오는 식으로 구성한 풀이

import random
male=['남자1호','남자2호','남자3호','남자4호','남자5호']
female=['여자1호','여자2호','여자3호','여자4호','여자5호']
couple=[]
for i in range(5):
    random.shuffle(male)
    random.shuffle(female)
    c=[male[0],female[0]]
    couple.append(c)
    del male[0]
    del female[0]
print((couple))


[['남자2호', '여자5호'], ['남자4호', '여자3호'], ['남자3호', '여자1호'], ['남자1호', '여자2호'], ['남자5호', '여자4호']]


In [17]:
# 랜덤 셔플을 사용하되 결과를 순서대로 짝지어 출력하는 풀이

from random import shuffle

male = ['정우성', '원 빈', '강동원', '조인성', '이광수']
female = ['김혜수', '신민아', '이나영', '천우희', '한예슬']

random.shuffle(male)
random.shuffle(female)

for i in range(0, 5):
    print(f'커플{i+1}: {male[i]} ♥️ {female[i]}')


커플1: 원 빈 ♥️ 신민아
커플2: 정우성 ♥️ 한예슬
커플3: 조인성 ♥️ 천우희
커플4: 강동원 ♥️ 김혜수
커플5: 이광수 ♥️ 이나영


In [22]:
# 선생님 풀이 (zip 함수 사용)

import random
m = list('12345')
f = list('abced')
random.shuffle(m)
random.shuffle(f)
couples = zip(m,f)

for i, j in enumerate(couples): # enumerate는 인덱스와 요소를 같이 출력
    print('커플 %d: %s와 %s' %(i+1, j[0], j[1]))
    

커플 1: 3와 b
커플 2: 1와 c
커플 3: 4와 e
커플 4: 5와 d
커플 5: 2와 a


In [122]:
#[과제] 입력받은 문자열의 각 문자를 그 다음 문자로 변경하여 출력하세요.
# abcde -> bcdea

word = list(input('문자열을 입력해 주세요. '))
word.append(word[0])
del word[0]
print(''.join(word))

문자열을 입력해 주세요. ㅇㅁㄴㅇㄴㅁㅇㅁㄴㅇㄴㅁ
ㅁㄴㅇㄴㅁㅇㅁㄴㅇㄴㅁㅇ


In [123]:
a=list(input("입력 : "))

for i in range(len(a)-1):
    print(a[i+1],end='')
print(a[0])

# 다음 글자의 값을 순서대로 붙여서 가로로 표현했다는 것

입력 : 또라이
라이또


In [125]:
sen = input()
print(sen[1:] + sen[0])


ㅇㅁㄴㅇㅁㄴㅇㅁㄴㅇㄴㅁㅇ
ㅁㄴㅇㅁㄴㅇㅁㄴㅇㄴㅁㅇㅇ


In [126]:
# 선생님 풀이

text = input('문장을 입력하세요 >> ')
ret = ''
for i in range(len(text)):
    if i != len(text)-1: # 글자가 문장 끝에 도달하지 못했다면
        ret+=text[i+1] # 그 다음 글자를 표기하라

    else: # 글자가 문장의 끝 단어라면
        ret+=text[0] # 제일 첫 번째 글자를 표기하라
print(ret)

문장을 입력하세요 >> 내가 널 얼마나 좋아하면 달에 네 목소리가 보여
가 널 얼마나 좋아하면 달에 네 목소리가 보여내


In [129]:
# [과제] 음식점의 음식 주문 가격 산출 프로그램을 자유롭게 작성하세요
# 딕셔너리 쓰면 될 듯? 음식 리스트 items으로 뽑아서 보여주고 values로 값을 반환하는?

menu = {'치킨마요':3500, '참치마요':3000, '포테이토마요':3300, '토핑':500}

print(f'''
오늘도 큰솥 도시락을 찾아주셔서 감사합니다.

    치킨마요 \ {menu['치킨마요']}
    참치마요 \ {menu['참치마요']}
포테이토마요 \ {menu['포테이토마요']}

※ 토핑 추가 \ {menu['토핑']}
''')
while 1:
    food = input('어떤 메뉴를 고르시겠어요? ')

    if food in menu:
        print(f'{food}의 가격은 {menu[food]}원입니다.')
        top = input('토핑을 추가하시겠어요? [네/아니오] ')
        if top=='네':
            print('주문하신 메뉴의 총 가격은 %d원입니다.\n맛있게 드세요.' %(int(menu[food])+int(menu['토핑'])))
            break
        elif top=='아니오':
            print(f'주문하신 메뉴의 총 가격은 {menu[food]}원입니다.\n맛있게 드세요.')
            break
        else: print('주문 오류입니다. 다시 주문해 주세요.')
    
    else: print('주문하신 메뉴는 없는 메뉴입니다.')



오늘도 큰솥 도시락을 찾아주셔서 감사합니다.

    치킨마요 \ 3500
    참치마요 \ 3000
포테이토마요 \ 3300

※ 토핑 추가 \ 500

어떤 메뉴를 고르시겠어요? 참치마요
참치마요의 가격은 3000원입니다.
토핑을 추가하시겠어요? [네/아니오] 아니오
주문하신 메뉴의 총 가격은 3000원입니다.
맛있게 드세요.


<img src = "식당.png"> <br> 이건 선생님이 들어주신 예시

In [39]:
# 수정해보자

# [과제] Player가 3승할 때까지 계속 진행되는 가위바위보 게임 프로그램을 작성하세요.
# 게임은 Player와 컴퓨터가 진행

# 가위바위보 작동 원리 넣기
# 누적 승리 횟수 체크
# 컴퓨터가 내는 가위바위보는 랜덤 결정 (리스트에서 고르는?)

import random

com = ['가위','바위','보']
victory = 0

print('게임을 시작하지. 가위 바위 보!')
print('중간에 그만두고 싶으면 x를 눌러 joy를 표해 주세요.')
while victory < 3:
    random.shuffle(com)
    hand = input('무엇을 낼까? >>> ')
    if hand == 'x':
        print('저기 겁쟁이가 도망간다!')
        break
    elif hand=='가위':
        if com[0]=='바위':
            print(f'컴퓨터의 선택: {com[0]}')
            print('졌쥬? 열받쥬? 크크루삥뽕\n')
            continue
        elif com[0]=='보':
            print(f'컴퓨터의 선택: {com[0]}')
            print('큭... 패배를 킹정하는 바...\n')
            victory+=1
            continue
    elif hand=='보':
        if com[0]=='가위':
            print(f'컴퓨터의 선택: {com[0]}')
            print('졌쥬? 열받쥬? 크크루삥뽕\n')
            continue
        elif com[0]=='바위':
            print(f'컴퓨터의 선택: {com[0]}')
            print('큭... 패배를 킹정하는 바...\n')
            victory+=1
            continue
    elif hand=='바위':
        if com[0]=='보':
            print(f'컴퓨터의 선택: {com[0]}')
            print('졌쥬? 열받쥬? 크크루삥뽕\n')
            continue
        elif com[0]=='가위':
            print(f'컴퓨터의 선택: {com[0]}')
            print('큭... 패배를 킹정하는 바...\n')
            victory+=1
            continue
    elif hand==com[0]:
        print(f'컴퓨터의 선택: {com[0]}')
        print('비겼쥬? 못 이기쥬?\n')
        continue
    else:
        print('가위바위보도 할 줄 모르쥬? 처음부터 다시 하쥬?')
        break
    print(f'남은 승리 횟수: {3-victory}회\n')
print('게임이 종료되었다! 하지만 기분이 썩 좋지 않은 것은 왜일까?')

게임을 시작하지. 가위 바위 보!
중간에 그만두고 싶으면 x를 눌러 joy를 표해 주세요.
무엇을 낼까? >>> 보
남은 승리 횟수: 3회

무엇을 낼까? >>> 보
컴퓨터의 선택: 바위
큭... 패배를 킹정하는 바...

무엇을 낼까? >>> 보
컴퓨터의 선택: 가위
졌쥬? 열받쥬? 크크루삥뽕

무엇을 낼까? >>> 보
남은 승리 횟수: 2회

무엇을 낼까? >>> 버
가위바위보도 할 줄 모르쥬? 처음부터 다시 하쥬?
게임이 종료되었다! 하지만 기분이 썩 좋지 않은 것은 왜일까?


In [25]:
import numpy as np

cnt = 0
rsp = ['가위', '바위', '보']

print("가위 바위 보 게임입니다. 3승할 때까지 계속 진행됩니다!")
print("그 전에 게임을 종료하고 싶다면 E를 입력해주세요.")

while cnt < 3:
    print()
    pl = input("무엇을 낼까요? (가위/바위/보) > ")
    if(pl=='E'): break
    elif(pl not in rsp):
        print("[가위] [바위] [보] 중 하나를 내주세요!")
        continue
    pc = rsp[np.random.randint(3)]
    print(f'컴퓨터 > {pc}')
    
    if(pl=='가위'):
        if(pc=='바위'):
            print("졌습니다. 다시 한 번 게임을 시작합니다!")
            continue
        elif(pc=='보'):
            print("게임에서 이겼습니다. 축하합니다!")
            cnt+=1
            continue
            
    elif(pl=='바위'):
        if(pc=='보'):
            print("졌습니다. 다시 한 번 게임을 시작합니다!")
            continue
        elif(pc=='가위'):
            print("게임에서 이겼습니다. 축하합니다!")
            cnt+=1
            continue
            
    elif(pl=='보'):
        if(pc=='가위'):
            print("졌습니다. 다시 한 번 게임을 시작합니다!")
            continue
        elif(pc=='바위'):
            print("게임에서 이겼습니다. 축하합니다!")
            cnt+=1
            continue
            
    print("비겼습니다. 다시 한 번 게임을 시작합니다!")
    
print("게임을 종료합니다. 수고하셨습니다.")

가위 바위 보 게임입니다. 3승할 때까지 계속 진행됩니다!
그 전에 게임을 종료하고 싶다면 E를 입력해주세요.

무엇을 낼까요? (가위/바위/보) > ㅇ
[가위] [바위] [보] 중 하나를 내주세요!

무엇을 낼까요? (가위/바위/보) > e
[가위] [바위] [보] 중 하나를 내주세요!

무엇을 낼까요? (가위/바위/보) > E
게임을 종료합니다. 수고하셨습니다.


In [ ]:
import random

com = ['가위','바위','보']
victory = 0

print('게임을 시작하지. 가위 바위 보!')
while victory < 3:
    random.shuffle(com)
    hand = input('무엇을 낼까? >>> ')
    if com[0] == '가위'and hand=='가위':
        print(f'컴퓨터의 선택: {com[0]}')
        print('비겼쥬? 못 이기쥬?\n')
        continue
    elif com[0] == '가위'and hand=='보':
        print(f'컴퓨터의 선택: {com[0]}')
        print('졌쥬? 열받쥬? 크크루삥뽕\n')
        continue
    elif com[0] == '가위'and hand=='바위':
        print(f'컴퓨터의 선택: {com[0]}')
        print('큭... 패배를 킹정하는 바...\n')
        victory+=1
    elif com[0] == '바위'and hand=='가위':
        print(f'컴퓨터의 선택: {com[0]}')
        print('졌쥬? 열받쥬? 크크루삥뽕\n')
        continue
    elif com[0] == '바위'and hand=='바위':
        print(f'컴퓨터의 선택: {com[0]}')
        print('비겼쥬? 못 이기쥬?\n')
        continue
    elif com[0] == '바위'and hand=='보':
        print(f'컴퓨터의 선택: {com[0]}')
        print('큭... 패배를 킹정하는 바...\n')
        victory+=1
    elif com[0] == '보'and hand=='가위':
        print(f'컴퓨터의 선택: {com[0]}')
        print('큭... 패배를 킹정하는 바...\n')
        victory+=1
    elif com[0] == '보'and hand=='바위':
        print(f'컴퓨터의 선택: {com[0]}')
        print('졌쥬? 열받쥬? 크크루삥뽕\n')
        continue
    elif com[0] == '보'and hand=='보':
        print(f'컴퓨터의 선택: {com[0]}')
        print('비겼쥬? 못 이기쥬?\n')
        continue
    else:
        print('가위바위보도 할 줄 모르쥬? 처음부터 다시 하쥬?')
        break
    print(f'남은 승리 횟수: {3-victory}회\n')
print('게임에서 승리했다! 하지만 기분이 썩 좋지 않은 것은 왜일까?')

In [15]:
# [과제] 컴퓨터가 랜덤하게 생성하는 숫자 맞추기 프로그램을 작성하세요.

# 1~10까지로 할까?
# 지금 컴퓨터가 무슨 숫자를 생각하고 있을지 입력하세요... 해서 ==로 매칭되면 축하
# 아니면 큰 수인지 작은 수인지 힌트를 주고
# 그런데 우리가 만드는 분기는 틀렸을 때에 있는 거니까 !=를 사용해야지

import numpy as np

num = np.random.randint(1,10)
print('지금 내가 생각하고 있는 숫자 맞춰 볼래?')

for i in range(charge):
    while guess != num :
        guess = int(input('1에서 10까지 골라봐~ >>> '))
        if guess>num:
            print('음... 조금만 더 낮춰 볼래?')
            continue
        elif guess<num:
            print('앗, 아쉽네~ 조금만 더 높여 봐!')
            continue
        else:
            print('축하해! 정답이야!')
            break


지금 내가 생각하고 있는 숫자 맞춰 볼래?
1에서 10까지 골라봐~ >>> 5
앗, 아쉽네~ 조금만 더 높여 봐!
1에서 10까지 골라봐~ >>> 7
앗, 아쉽네~ 조금만 더 높여 봐!
1에서 10까지 골라봐~ >>> 9
축하해! 정답이야!


In [131]:
import numpy as np
while(1):
    s_e=input("게임을 하시겠습니까?[y/n]: ")

    if(s_e=="y"):
        anser= np.random.randint(0,10)
        while(a != anser):
            a=int(input("숫자를 입력하세요(0~10): "))
            if(a>anser):
                print("down")
            elif(a<anser):
                print("up")
            else:
                print("범위 안의 숫자를 입력해주세요.")
        print("정답입니다.")
    else:
        print("게임을 종료합니다.")
        break


게임을 하시겠습니까?[y/n]: y
숫자를 입력하세요(0~10): 2
범위 안의 숫자를 입력해주세요.
정답입니다.
게임을 하시겠습니까?[y/n]: y
숫자를 입력하세요(0~10): 4
up
숫자를 입력하세요(0~10): 6
up
숫자를 입력하세요(0~10): 7
up
숫자를 입력하세요(0~10): 8
범위 안의 숫자를 입력해주세요.
정답입니다.
게임을 하시겠습니까?[y/n]: n
게임을 종료합니다.
